// Package templates hosts every Markdown template generated by sdt agent init
// as static, versioned .tmpl files under internal/templates/ and renders them
// through the stdlib text/template engine. The files are embedded into the
// binary with go:embed; cli/cmd supplies the per-template data and funcMap.
// See plan/20260924-190453-instruction-templates-static-embed.md.
package templates

import (
	"bytes"
	"embed"
	"fmt"
	"path/filepath"
	"text/template"
)

//go:embed workspace instructions
var templatesFS embed.FS

// The embed pattern is extended with each populated top-level directory
// (agents, commands, instructions, roles) as later migration phases land their
// template files.

// Render parses the embedded template at name (a path under templates/) and
// executes it with data. funcs adds template functions and may be nil for
// templates that need none.
func Render(name string, data any, funcs template.FuncMap) (string, error) {
	t, err := template.New(filepath.Base(name)).Funcs(funcs).ParseFS(templatesFS, name)
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.String(), nil
}

// Must is Render that panics on error, for init-time template values.
func Must(name string, data any, funcs template.FuncMap) string {
	s, err := Render(name, data, funcs)
	if err != nil {
		panic(fmt.Sprintf("render embedded template %s: %v", name, err))
	}
	return s
}