package cmd

import (
	"bufio"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
)

const (
	codeFence          = "```"
	agentTargetDefault = "AGENTS.md"
)

// ── tagged block helpers ───────────────────────────────────────────────────────

func agentTargetPath(cmd *cobra.Command) string {
	path := getStringFlag(cmd, "target", false)
	if path == "" {
		path = agentTargetDefault
	}
	return path
}

// ── agent command group ────────────────────────────────────────────────────────

var agentCmd = &cobra.Command{
	Use:   "agent",
	Short: "Agent instruction tools (AGENTS.md, instruction files)",
	Long: `Generate and maintain agent instruction files.

  agent init       bootstrap AGENTS.md + context/ instruction files

AGENTS.md carries the general agent instructions (5-stage lifecycle, knowledge
tiers, planning and work logs, communication, patterns) in a tagged
` + "`instructions`" + ` block, plus a write-once ` + "`project`" + ` block for project-specific
stack/build/test/lint/conventions. The instruction files under
` + "`context/instructions/`" + ` cover CLI usage plus per-type templates (analysis,
plan, tasks, decision, architecture, worklog, notes, questions, proposals, research, prompts) and the command
reference.
`,
}

// ── agent init (AGENTS.md + instruction files) ─────────────────────────────────

// instructionFile is one generated instruction file under context/instructions/.

type instructionFile struct {
	name string
	body string
}

func instructionFiles(project, group string) []instructionFile {
	return []instructionFile{
		{name: filepath.Base(sdtInstrProject), body: instrProjectTemplate(project, group)},
		{name: filepath.Base(sdtInstrAnalysis), body: instrAnalysisTemplate},
		{name: filepath.Base(sdtInstrPlan), body: instrPlanTemplate},
		{name: filepath.Base(sdtInstrTasks), body: instrTasksTemplate},
		{name: filepath.Base(sdtInstrDecision), body: instrDecisionTemplate},
		{name: filepath.Base(sdtInstrArchitecture), body: instrArchitectureTemplate},
		{name: filepath.Base(sdtInstrWorklog), body: instrWorklogTemplate},
		{name: filepath.Base(sdtInstrNotes), body: instrNotesTemplate},
		{name: filepath.Base(sdtInstrLessons), body: instrLessonsTemplate},
		{name: filepath.Base(sdtInstrQuestions), body: instrQuestionsTemplate},
		{name: filepath.Base(sdtInstrProposal), body: instrProposalTemplate},
		{name: filepath.Base(sdtInstrPrompts), body: instrPromptsTemplate},
		{name: filepath.Base(sdtInstrResearch), body: instrResearchTemplate},
		{name: filepath.Base(sdtInstrIngestion), body: instrIngestionTemplate},
		{name: filepath.Base(sdtInstrReference), body: instrReferenceTemplate},
		{name: filepath.Base(sdtInstrCli), body: instrCLITemplate},
		{name: filepath.Base(sdtInstrScripts), body: instrScriptsTemplate},
		{name: filepath.Base(sdtInstrWiki), body: instrWikiTemplate},
		{name: filepath.Base(sdtInstrDevelopment), body: instrDevelopmentTemplate},
	}
}

// obsoleteInstructionFiles were generated by older versions of sdt agent init
// and are no longer part of the generated set. With --force they are archived
// under context/archive/deprecated/ instead of removed.

var obsoleteInstructionFiles = []string{
	readmeFile,
	"commands.md",
	"workflow.md",
	"communication.md",
	"planning.md",
	"annotations.md",
	"self-update.md",
	"memory.md",
	// Renamed rfcs → proposals: the contract is now generated as proposal.md.
	"rfc.md",
	// Renamed adr → decision: the contract is now generated as decision.md.
	"adr.md",
}

// writeInstructionFiles creates the instruction files under context/instructions/.
// It is non-destructive: existing files are preserved unless force is set, and
// --force refreshes only the marker-delimited generated body. Obsolete files
// are archived instead of deleted.

func writeInstructionFiles(project, group string, force bool) []FileResult {
	scope := filepath.Base(sdtInstrDir)
	var results []FileResult
	for _, f := range instructionFiles(project, group) {
		path := filepath.Join(sdtInstrDir, f.name)
		results = append(results, agentWriteGeneratedFile(path, agentGeneratedMarkerName(scope, f.name), f.body, force))
	}
	if force {
		for _, name := range obsoleteInstructionFiles {
			results = append(results, agentArchiveGenerated(sdtInstrDir, name, "obsolete (no longer generated)"))
		}
	}
	return results
}

// agentCommandIDs are the agent-visible task triggers that get a thin command
// file under context/commands/. Each id maps to a durable contract at
// context/instructions/<id>.md; command files invoke/reference it, never move
// or duplicate it.

var agentCommandIDs = []string{
	"ingestion", "wiki", ctxTypeAnalysis, ctxTypePlan, ctxTypeTasks, ctxTypeProposal,
	ctxTypeDecision, ctxTypeArchitecture, ctxTypeWorklog, ctxTypeNotes, ctxTypeQuestions,
	"prompts", "reference", ctxTypeResearch,
}

// commandFiles returns the generated command files under context/commands/:
// one thin trigger per agent-visible task plus the index. The index is built
// last from a directory scan so user-created triggers are listed too and
// survive `sdt agent init --force`.

func commandFiles(project string, now time.Time) []instructionFile {
	var files []instructionFile
	for _, id := range agentCommandIDs {
		files = append(files, instructionFile{name: id + ".md", body: instrCommandStubTemplate(id, id, project, now)})
	}
	files = append(files, instructionFile{name: filepath.Base(sdtCommandsIndex), body: commandsIndexContent(project, now)})
	return files
}

// obsoleteCommandFiles were generated as command stubs by older versions of
// sdt agent init and are no longer part of the generated set. With --force they
// are archived under context/archive/deprecated/ instead of removed.

var obsoleteCommandFiles = []string{
	// Renamed rfcs → proposals: the trigger stub is now proposal.md.
	"rfc.md",
	// Renamed adr → decision: the trigger stub is now decision.md.
	"adr.md",
}

// writeCommandFiles creates the command files under context/commands/. It is
// non-destructive: existing files are preserved unless force is set, and
// --force refreshes only the marker-delimited generated body. Obsolete files
// are archived instead of deleted.

func writeCommandFiles(project string, force bool) []FileResult {
	now := time.Now()
	scope := filepath.Base(sdtCommandsDir)
	var results []FileResult
	for _, f := range commandFiles(project, now) {
		path := filepath.Join(sdtCommandsDir, f.name)
		results = append(results, agentWriteGeneratedFile(path, agentGeneratedMarkerName(scope, f.name), f.body, force))
	}
	if force {
		for _, name := range obsoleteCommandFiles {
			results = append(results, agentArchiveGenerated(sdtCommandsDir, name, "obsolete (no longer generated)"))
		}
	}
	return results
}

var agentInitCmd = &cobra.Command{
	Use:   useInit,
	Short: "Bootstrap an SDT-managed project for AI agents",
	Long: `Bootstrap the current directory with everything an AI agent needs:

  .sdt.yaml                           project identity (project/group)
  AGENTS.md                           instructions block + optional write-once project template
  context/plan|worklog|notes|tasks|archive|tmp|scripts  working directories
  context/proposals/     proposals awaiting review
  context/prompts/       tracked prompts (run/review)
  context/research/      research notes and findings
  context/architecture/  living architecture documentation (no date)
  context/decisions/     numbered decisions (NNNN-<slug>.md, append-only)
  context/questions/     open questions awaiting a user decision
  context/analysis/      analysis documents and implementation plans
  context/wiki/          wiki pages (grouped in subpaths, no date)
  context/commands/      thin per-trigger command files
  context/instructions/  per-type instruction/template files
  .gitignore                          ignores chosen context dirs (current dir)

The command is idempotent and non-destructive: a second run fills in missing
content and never overwrites or removes existing files. Use --force to refresh
the generated (marker-delimited) content while preserving edits outside the
markers, and to archive obsolete instruction/command files instead of deleting
them.

The .gitignore entries for the context working directories are decided
interactively: you are asked whether to ignore them at all, and which entries
(tmp/, docs/, or the whole context/ directory). The file is created or
updated in the execution directory — the same directory as .sdt.yaml — even
when it is not a git repository; parent directories are never resolved. Use
--gitignore none|tmp|docs|work|context to pick non-interactively; work (tmp/ +
docs/ entries) is the default. --yes accepts that default without prompting.

The write-once project block (<!-- sdt:begin:project -->) is optional: you
are asked whether to insert it (default no), or pass --project-block to insert
it non-interactively. Declining never removes an existing block; re-running
never modifies a present block. The agent fills empty sections from project
evidence, asking first (see the hard rules in the instructions block).

Values not provided via flags are prompted interactively with sensible defaults.
Use --yes to accept defaults without prompting (CI/non-interactive).

Examples:
  sdt agent init
  sdt agent init --project myapp
  sdt agent init --project myapp --group platform --yes`,
	Run: func(cmd *cobra.Command, args []string) {
		yes := getBoolFlag(cmd, "yes", false)
		project := getStringFlag(cmd, "project", false)
		group := getStringFlag(cmd, "group", false)
		force := getBoolFlag(cmd, "force", false)
		target := agentTargetPath(cmd)

		// 1. Resolve project identity: flags > interactive prompt > default.
		if project == "" {
			project = agentPrompt(cmd, yes, "Project name", defaultProjectName())
		}
		if group == "" {
			group = agentPrompt(cmd, yes, "Group name", defaultProjectName())
		}

		cfg := &ProjectConfig{Project: project, Group: group}
		if _, err := os.Stat(sdtConfigFile); err == nil {
			existing := loadProjectConfig(sdtConfigFile)
			if existing != nil {
				cfg.fill(existing)
			}
		}
		configResult := FileResult{Path: sdtConfigFile}
		if err := os.WriteFile(sdtConfigFile, []byte(buildProjectConfigContent(cfg.Project, cfg.Group)), 0o600); err != nil { //#nosec G306 -- user project config
			exitWithError(cmd, err)
		}
		configResult.Status = statusWritten

		// 2. context/ working directories (non-destructive).
		dirResults := ensureWorkDirs(force)

		// 3. .gitignore: entries maintained in the execution directory (the .sdt.yaml
		//    location) — asked/picked even outside a git repository, never
		//    resolved from a parent.
		var gitIgnoreResults []FileResult
		if res := ensureGitIgnore(resolveGitIgnoreMode(cmd, yes)); res != nil {
			gitIgnoreResults = append(gitIgnoreResults, *res)
		}

		// 4. Instruction files under context/instructions/.
		instrResults := writeInstructionFiles(cfg.Project, cfg.Group, force)

		// 4b. Command files under context/commands/ (thin agent-invokable
		//     triggers; contracts stay in context/instructions/).
		cmdResults := writeCommandFiles(cfg.Project, force)

		// 5. AGENTS.md: ensure the instructions block (--force refreshable) and,
		//    unless declined, the write-once project block. Prompts only when
		//    interactive; --project-block forces insertion non-interactively;
		//    --yes and non-TTY runs default to no block.
		wantProject := getBoolFlag(cmd, "project-block", false)
		if !wantProject {
			wantProject = agentPromptBool(cmd, yes, "Insert the `<!-- sdt:begin:project -->` block into AGENTS.md?", false)
		}
		mdResult, mdBody := agentMergeTarget(target, cfg.Project, cfg.Group, force, wantProject)
		if err := os.WriteFile(target, []byte(mdBody), 0o644); err != nil { //#nosec G306 -- user-chosen output file
			exitWithError(cmd, err)
		}

		results := []FileResult{configResult}
		results = append(results, dirResults...)
		results = append(results, gitIgnoreResults...)
		results = append(results, instrResults...)
		results = append(results, cmdResults...)
		results = append(results, mdResult)
		outputFileResults(cmd, results)
	},
}

// agentPrompt asks for a value on the terminal. When yes is set, or stdin is
// not a terminal, the default is returned without prompting.

func agentPrompt(cmd *cobra.Command, yes bool, label, def string) string {
	if yes || !stdinIsTTY() {
		return def
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "%s [%s]: ", label, def); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// resolveGitIgnoreMode decides which context entries go into .gitignore.
// A --gitignore flag value wins. When omitted the mode is asked interactively
// (confirm first, then which entries); non-interactive runs and --yes default
// to work, preserving the historical behavior.

func agentPromptBool(cmd *cobra.Command, yes bool, label string, def bool) bool {
	if yes || !stdinIsTTY() {
		return def
	}
	d := "n"
	if def {
		d = "y"
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "%s [%s]: ", label, d); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes", "1":
		return true
	case "n", "no", "0":
		return false
	}
	if b, perr := strconv.ParseBool(strings.TrimSpace(line)); perr == nil {
		return b
	}
	return def
}

// agentPromptGitIgnoreMode asks which context entries to ignore. Accepted
// input is a comma-separated list of numbers or keywords: 1/tmp, 2/docs,
// 3/context (entire directory), or work for both tmp and docs. Empty input and
// unrecognized tokens fall back to def.

func stdinIsTTY() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return fi.Mode()&os.ModeCharDevice != 0
}

func defaultProjectName() string {
	cwd, err := os.Getwd()
	if err != nil {
		return ""
	}
	sum := sha256.Sum256([]byte(cwd))
	return fmt.Sprintf("%s_%x", filepath.Base(cwd), sum[:4])
}

// loadProjectConfig reads a project config file, returning nil on any error.

func loadProjectConfig(path string) *ProjectConfig {
	data, err := os.ReadFile(path) //#nosec G304 -- user-chosen config path
	if err != nil {
		return nil
	}
	var cfg ProjectConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil
	}
	return &cfg
}

// fill copies non-empty fields from existing into cfg, preserving prior values.
func (cfg *ProjectConfig) fill(existing *ProjectConfig) {
	if existing == nil {
		return
	}
	if existing.Project != "" {
		cfg.Project = existing.Project
	}
	if existing.Group != "" {
		cfg.Group = existing.Group
	}
}

// ensureWorkDirs creates the context/ working directory layout.

func ensureWorkDirs(force bool) []FileResult {
	dirs := []string{sdtWorkDir, sdtPlanDir, sdtAnalysisDir, sdtWorklogDir, sdtNotesDir, sdtTasksDir, sdtArchiveDir, sdtTmpDir, sdtInstrDir, sdtCommandsDir, sdtArchitectureDir, sdtDecisionsDir, sdtQuestionsDir, sdtProposalsDir, sdtPromptsDir, sdtResearchDir, sdtScriptsDir}
	var results []FileResult
	for _, d := range dirs {
		res := FileResult{Path: d + "/"}
		fi, err := os.Stat(d)
		if err == nil {
			if fi.IsDir() {
				res.Status = statusSkipped
				res.Reason = "directory already exists"
			} else {
				res.Status = statusError
				res.Reason = "exists and is not a directory"
			}
		} else if os.IsNotExist(err) {
			if err := os.MkdirAll(d, 0o750); err != nil { //#nosec G301
				res.Status = statusError
				res.Reason = err.Error()
			} else {
				res.Status = statusCreated
			}
		} else {
			res.Status = statusError
			res.Reason = err.Error()
		}
		results = append(results, res)
	}

	files := []struct {
		path    string
		content string
	}{
		{sdtWorkReadme, sdtWorkReadmeContent()},
		{sdtScriptsIndex, scriptsIndexTemplate},
	}
	for _, f := range files {
		res := FileResult{Path: f.path}
		if _, err := os.Stat(f.path); os.IsNotExist(err) {
			if err := os.WriteFile(f.path, []byte(f.content), 0o644); err != nil { //#nosec G306 -- user-chosen output
				res.Status = statusError
				res.Reason = err.Error()
			} else {
				res.Status = statusCreated
			}
		} else if err == nil {
			res.Status = statusSkipped
			res.Reason = "file already exists"
		} else {
			res.Status = statusError
			res.Reason = err.Error()
		}
		results = append(results, res)
	}
	return results
}

const sdtWorkReadmeTemplate = `# context/ — Working Directory

This directory holds the agent's planning, work logs, task lists, notes,
instruction files and temporary files for this project.

## Layout

- ` + "`plan/`" + ` — plans written before starting non-trivial work
- ` + "`analysis/`" + ` — analysis documents and implementation plans
- ` + "`proposals/`" + ` — proposals waiting for review and a decision
- ` + "`research/`" + ` — research notes and findings
- ` + "`prompts/`" + ` — tracked prompts (created and re-run)
- ` + "`wiki/`" + ` — wiki pages, named ` + "`<slug>`" + ` or ` + "`subpath/<slug>`" + ` (no date)
- ` + "`architecture/`" + ` — living architecture documentation (no date in name)
- ` + "`decisions/`" + ` — numbered decisions (` + "`NNNN-<slug>.md`" + `, append-only)
- ` + "`worklog/`" + ` — chronological log of completed work
- ` + "`notes/`" + ` — free-form annotations
- ` + "`questions/`" + ` — open questions / points awaiting user decision (` + "`sources`" + ` link back to origin)
- ` + "`tasks/`" + ` — per-phase task checklists
- ` + "`archive/`" + ` — archived documents (history)
- ` + "`commands/`" + ` — thin agent-invokable trigger files (` + "`context/commands/<trigger>.md`" + `)
- ` + "`instructions/`" + ` — agent instruction files (referenced by AGENTS.md)
- ` + "`scripts/`" + ` — reusable utility scripts (` + "`index.md`" + ` lists them; see ` + "`instructions/scripts.md`" + `)
- ` + "`index.md`" + ` — generated knowledge index (reindex/lint)
- ` + "`tmp/`" + ` — temporary and scratch files (never outside this project)

## Conventions

- Files are prefixed with date/time so they sort naturally and keep history:
  - ` + "`context/plan/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`context/analysis/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`context/worklog/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`context/notes/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`context/tasks/<YYYYMMDD-HHMMSS>-<slug-plan>-phase-<n>.md`" + ` — checklist per plan phase
  - ` + "`context/archive/<YYYYMMDD-HHMMSS>-<slug>.md`" + ` — archived documents
- ` + "`architecture/`" + ` files are living documents without a date; decisions are
  append-only and numbered (` + "`decisions/0001-<slug>.md`" + `).
- ` + "`context/`" + ` files use concise technical language. Cut fluff,
  keep meaning and readability (token-efficient).
- Every work file starts with YAML frontmatter:

` + "```yaml" + `
---
kind: worklog      # plan | worklog | notes | tasks
summary: <one-line description>   # mandatory (index source)
context: what triggered this entry
status: active
created: <ISO 8601>
updated: <ISO 8601>
links:                            # optional array of related docs
  - decisions/0001-something
project: <project>
---
` + "```" + `

Store durable facts in ` + "`decisions/`" + ` (decisions) and ` + "`architecture/`" + `; the rest of
the directory keeps the chronological work history.

`

// sdtWorkReadmeContent renders the generated context/README.md, deriving the
// command examples' type lists from the document-type registry so they never
// drift from the surfaces they document.

func sdtWorkReadmeContent() string {
	return sdtWorkReadmeTemplate + `## Commands

Create and manage work files with ` + "`sdt context`" + `:

- ` + "`sdt context new --type " + ctxTypeHelpText(ctxNewTypes()) + " --slug <slug> [--input ...]`" + ` — create a
  file with the correct name and frontmatter
- ` + "`sdt context reindex`" + ` / ` + "`sdt context lint`" + ` — regenerate ` + "`index.md`" + ` / validate
  frontmatter and links
- ` + "`sdt context template --type <tipo>`" + ` — print the per-type instruction file
- ` + "`sdt context path --type " + ctxTypeHelpText(ctxPathTypes()) + " [--slug]`" + ` — print a
  path without creating anything
- ` + "`sdt context list --type " + ctxListHelpText() + "`" + ` — list existing files
- ` + "`sdt context task add --phase <phase> \"<step>\"`" + ` / ` + "`done|block|wip <id>`" + ` — manage a
  per-phase task checklist
`
}

// gitIgnore modes for --gitignore and the interactive entries prompt.
const (
	gitIgnoreModeNone    = "none"    // leave .gitignore untouched
	gitIgnoreModeTmp     = "tmp"     // ignore context/tmp/
	gitIgnoreModeDocs    = "docs"    // ignore context/sdtdocs/
	gitIgnoreModeWork    = "work"    // ignore tmp/ + docs/ (default)
	gitIgnoreModeContext = "context" // ignore the whole context/
)

// gitIgnoreTmpEntry keeps context/tmp out of version control. The pattern is
// not root-anchored so it also applies when context lives in a subdirectory.

func init() {
	agentInitCmd.Flags().String("project", "", "Project name")
	agentInitCmd.Flags().String("group", "", "Group name")
	agentInitCmd.Flags().String("target", agentTargetDefault, "Output instruction file")
	agentInitCmd.Flags().String("gitignore", "", "Which context entries to add to .gitignore (none, tmp, docs, work, context); prompts interactively when omitted")
	agentInitCmd.Flags().Bool("force", false, "Refresh generated template content")
	agentInitCmd.Flags().Bool("project-block", false, "Insert the write-once <!-- sdt:begin:project --> block (asks interactively when omitted)")
	agentInitCmd.Flags().Bool("yes", false, "Accept defaults without prompting")

	agentCmd.AddCommand(agentInitCmd, agentVerifyCmd)
	rootCmd.AddCommand(agentCmd)
}
