package cmd

import (
	"bufio"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
)

const (
	codeFence          = "```"
	agentTargetDefault = "AGENTS.md"
)

// ── tagged block helpers ───────────────────────────────────────────────────────

func sectionBlock(name, body string) string {
	body = strings.TrimSpace(body)
	return fmt.Sprintf("<!-- sdt:begin:%s -->\n\n%s\n\n<!-- sdt:end:%s -->\n", name, body, name)
}

func sectionBeginMarker(name string) string {
	return "<!-- sdt:begin:" + name + " -->"
}

func sectionEndMarker(name string) string {
	return "<!-- sdt:end:" + name + " -->"
}

func sectionRegexp(name string) *regexp.Regexp {
	return regexp.MustCompile(`(?s)\n?` + regexp.QuoteMeta(sectionBeginMarker(name)) + `.*?` + regexp.QuoteMeta(sectionEndMarker(name)) + `\n?`)
}

func hasSection(content, name string) bool {
	return sectionRegexp(name).MatchString(content)
}

// agentMergeBlock ensures the named block exists in content. With force it is
// refreshed, otherwise left untouched when already present. Returns the new
// content and whether it changed.
func agentMergeBlock(content, name, body string, force bool) (string, bool) {
	if hasSection(content, name) {
		if force {
			return sectionRegexp(name).ReplaceAllString(content, "\n"+sectionBlock(name, body)), true
		}
		return content, false
	}
	content = strings.TrimRight(content, "\n")
	if content != "" {
		content += "\n\n"
	}
	return content + sectionBlock(name, body), true
}

// ── target file helpers ────────────────────────────────────────────────────────

func agentTargetPath(cmd *cobra.Command) string {
	path := getStringFlag(cmd, "target", false)
	if path == "" {
		path = agentTargetDefault
	}
	return path
}

// ── agent command group ────────────────────────────────────────────────────────

var agentCmd = &cobra.Command{
	Use:   "agent",
	Short: "Agent instruction tools (AGENTS.md, instruction files)",
	Long: `Generate and maintain agent instruction files.

  agent init       bootstrap AGENTS.md + sdt.context/ instruction files

AGENTS.md carries the general agent instructions (workflow, planning and work
logs, communication, patterns) in a single tagged block. The instruction files
under ` + "`sdt.context/instructions/`" + ` cover CLI usage only (project,
memory, command reference, CLI usage and examples).
`,
}

// ── agent init (AGENTS.md + instruction files) ─────────────────────────────────

// instructionFile is one generated instruction file under sdt.context/instructions/.
type instructionFile struct {
	name string
	body string
}

func instructionFiles(project, group string) []instructionFile {
	return []instructionFile{
		{name: filepath.Base(sdtInstrProject), body: instrProjectTemplate(project, group)},
		{name: filepath.Base(sdtInstrMemory), body: instrMemoryTemplate},
		{name: filepath.Base(sdtInstrReference), body: instrReferenceTemplate},
		{name: filepath.Base(sdtInstrCli), body: instrCLITemplate},
	}
}

// obsoleteInstructionFiles were generated by older versions of sdt agent init
// and are no longer part of the generated set. With --force they are removed.
var obsoleteInstructionFiles = []string{
	readmeFile,
	"commands.md",
	"workflow.md",
	"communication.md",
	"planning.md",
	"annotations.md",
	"self-update.md",
}

// writeInstructionFiles creates the instruction files under sdt.context/instructions/.
// It is non-destructive: existing files are preserved unless force is set.
func writeInstructionFiles(project, group string, force bool) []FileResult {
	var results []FileResult
	for _, f := range instructionFiles(project, group) {
		path := filepath.Join(sdtInstrDir, f.name)
		res := FileResult{Path: path}
		existed := false
		if _, err := os.Stat(path); err == nil {
			existed = true
			if !force {
				res.Status = statusSkipped
				res.Reason = "file already exists (use --force to overwrite)"
				results = append(results, res)
				continue
			}
		} else if !os.IsNotExist(err) {
			res.Status = statusError
			res.Reason = err.Error()
			results = append(results, res)
			continue
		}
		if err := os.MkdirAll(sdtInstrDir, 0o750); err != nil { //#nosec G301
			res.Status = statusError
			res.Reason = err.Error()
			results = append(results, res)
			continue
		}
		if err := os.WriteFile(path, []byte(f.body), 0o644); err != nil { //#nosec G306 -- user-chosen output
			res.Status = statusError
			res.Reason = err.Error()
			results = append(results, res)
			continue
		}
		if existed {
			res.Status = statusUpdated
		} else {
			res.Status = statusCreated
		}
		results = append(results, res)
	}
	if force {
		for _, name := range obsoleteInstructionFiles {
			path := filepath.Join(sdtInstrDir, name)
			if _, err := os.Stat(path); os.IsNotExist(err) {
				continue
			} else if err != nil {
				results = append(results, FileResult{Path: path, Status: statusError, Reason: err.Error()})
				continue
			}
			if err := os.Remove(path); err != nil {
				results = append(results, FileResult{Path: path, Status: statusError, Reason: err.Error()})
				continue
			}
			results = append(results, FileResult{Path: path, Status: statusRemoved, Reason: "obsolete (no longer generated)"})
		}
	}
	return results
}

var agentInitCmd = &cobra.Command{
	Use:   useInit,
	Short: "Bootstrap an SDT-managed project for AI agents",
	Long: `Bootstrap the current directory with everything an AI agent needs:

  .sdt.yaml                           project identity (project/group)
  AGENTS.md                           single tagged block of general instructions
  sdt.context/plan|worklog|notes|tasks|archive|tmp  working directories
  sdt.context/analysis/          analysis documents and implementation plans
  sdt.context/memory/            persistent file-based memory (README.md + index.md + pages/)
  sdt.context/instructions/      CLI usage files (project, memory, reference, cli usage)
  .gitignore                          ignores chosen sdt.context dirs (git repos only)

The command is idempotent and non-destructive: a second run fills in missing
content and never overwrites or removes existing files. Use --force to refresh
generated content and remove obsolete instruction files.

When the current directory is inside a git repository, the .gitignore entries
for the sdt.context working directories are decided interactively: you are asked
whether to ignore them at all, and which entries (tmp/, docs/, or the whole
sdt.context/ directory). Use --gitignore none|tmp|docs|work|context to pick
non-interactively; work (tmp/ + docs/ entries) is the default. --yes accepts
that default without prompting.

Values not provided via flags are prompted interactively with sensible defaults.
Use --yes to accept defaults without prompting (CI/non-interactive).

Examples:
  sdt agent init
  sdt agent init --project myapp
  sdt agent init --project myapp --group platform --yes`,
	Run: func(cmd *cobra.Command, args []string) {
		yes := getBoolFlag(cmd, "yes", false)
		project := getStringFlag(cmd, "project", false)
		group := getStringFlag(cmd, "group", false)
		force := getBoolFlag(cmd, "force", false)
		target := agentTargetPath(cmd)

		// 1. Resolve project identity: flags > interactive prompt > default.
		if project == "" {
			project = agentPrompt(cmd, yes, "Project name", defaultProjectName())
		}
		if group == "" {
			group = agentPrompt(cmd, yes, "Group name", defaultProjectName())
		}

		cfg := &ProjectConfig{Project: project, Group: group}
		if _, err := os.Stat(sdtConfigFile); err == nil {
			existing := loadProjectConfig(sdtConfigFile)
			if existing != nil {
				cfg.fill(existing)
			}
		}
		configResult := FileResult{Path: sdtConfigFile}
		if err := os.WriteFile(sdtConfigFile, []byte(buildProjectConfigContent(cfg.Project, cfg.Group)), 0o600); err != nil { //#nosec G306 -- user project config
			exitWithError(cmd, err)
		}
		configResult.Status = statusWritten

		// 2. sdt.context/ working directories (non-destructive).
		dirResults := ensureWorkDirs(force)

		// 3. .gitignore: add the chosen sdt.context entries when inside a git repository.
		var gitIgnoreResults []FileResult
		if res := ensureGitIgnore(resolveGitIgnoreMode(cmd, yes)); res != nil {
			gitIgnoreResults = append(gitIgnoreResults, *res)
		}

		// 4. Instruction files under sdt.context/instructions/.
		instrResults := writeInstructionFiles(cfg.Project, cfg.Group, force)

		// 5. AGENTS.md: ensure the single instructions block.
		mdResult, mdBody := agentMergeTarget(target, cfg.Project, cfg.Group, force)
		if err := os.WriteFile(target, []byte(mdBody), 0o644); err != nil { //#nosec G306 -- user-chosen output file
			exitWithError(cmd, err)
		}

		results := []FileResult{configResult}
		results = append(results, dirResults...)
		results = append(results, gitIgnoreResults...)
		results = append(results, instrResults...)
		results = append(results, mdResult)
		outputFileResults(cmd, results)
	},
}

// agentPrompt asks for a value on the terminal. When yes is set, or stdin is
// not a terminal, the default is returned without prompting.
func agentPrompt(cmd *cobra.Command, yes bool, label, def string) string {
	if yes || !stdinIsTTY() {
		return def
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "%s [%s]: ", label, def); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// resolveGitIgnoreMode decides which sdt.context entries go into .gitignore.
// A --gitignore flag value wins. When omitted the mode is asked interactively
// (confirm first, then which entries); non-interactive runs and --yes default
// to work, preserving the historical behavior.
func resolveGitIgnoreMode(cmd *cobra.Command, yes bool) string {
	raw := strings.ToLower(strings.TrimSpace(getStringFlag(cmd, "gitignore", false)))
	if raw != "" {
		switch raw {
		case gitIgnoreModeNone, gitIgnoreModeTmp, gitIgnoreModeDocs, gitIgnoreModeWork, gitIgnoreModeContext:
			return raw
		}
		exitWithError(cmd, fmt.Errorf("invalid --gitignore %q (want one of none|tmp|docs|work|context)", raw))
	}
	if yes || !stdinIsTTY() {
		return gitIgnoreModeWork
	}
	if !agentPromptBool(cmd, false, "Add sdt.context working directories to .gitignore?", true) {
		return gitIgnoreModeNone
	}
	return agentPromptGitIgnoreMode(cmd, false, gitIgnoreModeWork)
}

// agentPromptBool asks a yes/no question on the terminal. When yes is set, or
// stdin is not a terminal, the default is returned without prompting.
func agentPromptBool(cmd *cobra.Command, yes bool, label string, def bool) bool {
	if yes || !stdinIsTTY() {
		return def
	}
	d := "n"
	if def {
		d = "y"
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "%s [%s]: ", label, d); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes", "1":
		return true
	case "n", "no", "0":
		return false
	}
	if b, perr := strconv.ParseBool(strings.TrimSpace(line)); perr == nil {
		return b
	}
	return def
}

// agentPromptGitIgnoreMode asks which sdt.context entries to ignore. Accepted
// input is a comma-separated list of numbers or keywords: 1/tmp, 2/docs,
// 3/context (entire directory), or work for both tmp and docs. Empty input and
// unrecognized tokens fall back to def.
func agentPromptGitIgnoreMode(cmd *cobra.Command, yes bool, def string) string {
	if yes || !stdinIsTTY() {
		return def
	}
	if _, ferr := fmt.Fprintln(cmd.ErrOrStderr(), "Which sdt.context entries should be added to .gitignore?"); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "  1) %s\n", gitIgnoreTmpEntry); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "  2) %s\n", gitIgnoreDocsEntry); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "  3) %s (entire working directory)\n", gitIgnoreContextEntry); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprint(cmd.ErrOrStderr(), "Comma-separated (1,2,3) or keywords (tmp, docs, context) [1,2]: "); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	sel := strings.ToLower(strings.TrimSpace(line))
	if sel == "" {
		return def
	}
	selected := map[string]bool{}
	for _, part := range strings.Split(sel, ",") {
		choice := strings.TrimSpace(part)
		switch choice {
		case "1", gitIgnoreModeTmp:
			selected[gitIgnoreModeTmp] = true
		case "2", gitIgnoreModeDocs:
			selected[gitIgnoreModeDocs] = true
		case "3", gitIgnoreModeContext, "all":
			return gitIgnoreModeContext
		case gitIgnoreModeWork:
			return gitIgnoreModeWork
		}
	}
	if selected[gitIgnoreModeTmp] && selected[gitIgnoreModeDocs] {
		return gitIgnoreModeWork
	}
	if selected[gitIgnoreModeTmp] {
		return gitIgnoreModeTmp
	}
	if selected[gitIgnoreModeDocs] {
		return gitIgnoreModeDocs
	}
	return def
}

func stdinIsTTY() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return fi.Mode()&os.ModeCharDevice != 0
}

func defaultProjectName() string {
	cwd, err := os.Getwd()
	if err != nil {
		return ""
	}
	sum := sha256.Sum256([]byte(cwd))
	return fmt.Sprintf("%s_%x", filepath.Base(cwd), sum[:4])
}

// loadProjectConfig reads a project config file, returning nil on any error.
func loadProjectConfig(path string) *ProjectConfig {
	data, err := os.ReadFile(path) //#nosec G304 -- user-chosen config path
	if err != nil {
		return nil
	}
	var cfg ProjectConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil
	}
	return &cfg
}

// fill copies non-empty fields from existing into cfg, preserving prior values.
func (cfg *ProjectConfig) fill(existing *ProjectConfig) {
	if existing == nil {
		return
	}
	if existing.Project != "" {
		cfg.Project = existing.Project
	}
	if existing.Group != "" {
		cfg.Group = existing.Group
	}
}

// ensureWorkDirs creates the sdt.context/ working directory layout.
func ensureWorkDirs(force bool) []FileResult {
	dirs := []string{sdtWorkDir, sdtPlanDir, sdtAnalysisDir, sdtWorklogDir, sdtNotesDir, sdtTasksDir, sdtArchiveDir, sdtTmpDir, sdtInstrDir, sdtMemoryDir, sdtMemoryPagesDir}
	var results []FileResult
	for _, d := range dirs {
		res := FileResult{Path: d + "/"}
		fi, err := os.Stat(d)
		if err == nil {
			if fi.IsDir() {
				res.Status = statusSkipped
				res.Reason = "directory already exists"
			} else {
				res.Status = statusError
				res.Reason = "exists and is not a directory"
			}
		} else if os.IsNotExist(err) {
			if err := os.MkdirAll(d, 0o750); err != nil { //#nosec G301
				res.Status = statusError
				res.Reason = err.Error()
			} else {
				res.Status = statusCreated
			}
		} else {
			res.Status = statusError
			res.Reason = err.Error()
		}
		results = append(results, res)
	}

	files := []struct {
		path    string
		content string
	}{
		{sdtWorkReadme, sdtWorkReadmeTemplate},
		{sdtMemoryReadme, sdtMemoryReadmeTemplate},
		{sdtMemoryIndex, sdtMemoryIndexTemplate},
	}
	for _, f := range files {
		res := FileResult{Path: f.path}
		if _, err := os.Stat(f.path); os.IsNotExist(err) {
			if err := os.WriteFile(f.path, []byte(f.content), 0o644); err != nil { //#nosec G306 -- user-chosen output
				res.Status = statusError
				res.Reason = err.Error()
			} else {
				res.Status = statusCreated
			}
		} else if err == nil {
			res.Status = statusSkipped
			res.Reason = "file already exists"
		} else {
			res.Status = statusError
			res.Reason = err.Error()
		}
		results = append(results, res)
	}
	return results
}

const sdtMemoryReadmeTemplate = `# sdt.context/memory/ — File-based Memory

Durable project memory as plain Markdown: decisions, constraints, concepts and
references that must survive sessions. No database, no daemon — files only,
fully offline.

## Layout

- ` + "`pages/<id>.md`" + ` — one durable unit of knowledge per file
- ` + "`index.md`" + ` — page index (` + "`[[id]]`" + ` + one-line summary)
- ` + "`README.md`" + ` — this protocol

## Page format

Each page carries frontmatter (` + "`id`" + `, ` + "`title`" + `, ` + "`category`" + `, ` + "`status`" + `, ` + "`tags`" + `,
` + "`created`" + `, ` + "`updated`" + `), a ` + "`<!-- compiled_truth -->`" + ` section (current best
understanding) and an append-only ` + "`## Timeline`" + `. Category is one of:
` + "`decision`" + ` | ` + "`concept`" + ` | ` + "`project`" + ` | ` + "`person`" + ` | ` + "`reference`" + `. The ` + "`id`" + `
is kebab-case and must equal the filename.

## Rules

- compiled_truth is rewritable; the timeline is append-only — every truth change
  appends a timeline entry, every overturn appends ` + "`kind: reversal`" + `.
- Reference pages with ` + "`[[id]]`" + `; keep ` + "`index.md`" + ` updated.
- Write in the user's working language; keep ids, tags and paths verbatim.
- The test: will this still matter in six months, and is it hard to reconstruct
  from the code or git?

Full operating skill: ` + "`sdt.context/instructions/memory.md`" + `.
`

const sdtMemoryIndexTemplate = `# Memory Index

_Auto-maintained by the agent. List pages as ` + "`[[id]]`" + ` — one-line summary; keep in sync when pages are created, updated or archived._
`

const sdtWorkReadmeTemplate = `# sdt.context/ — Working Directory

This directory holds the agent's planning, work logs, task lists, notes,
instruction files and temporary files for this project.

## Layout

- ` + "`plan/`" + ` — plans written before starting non-trivial work
- ` + "`analysis/`" + ` — analysis documents and implementation plans
- ` + "`worklog/`" + ` — chronological log of completed work
- ` + "`notes/`" + ` — free-form annotations
- ` + "`tasks/`" + ` — active task list (` + "`TODO.md`" + `)
- ` + "`archive/`" + ` — completed task lists (history)
- ` + "`instructions/`" + ` — agent instruction files (referenced by AGENTS.md)
- ` + "`memory/`" + ` — durable file-based memory (` + "`memory/pages/`" + `, protocol in ` + "`memory/README.md`" + `)
- ` + "`tmp/`" + ` — temporary and scratch files (never outside this project)

## Conventions

- Files are prefixed with date/time so they sort naturally and keep history:
  - ` + "`sdt.context/plan/<YYYY-MM-DD>-<slug>.md`" + `
  - ` + "`sdt.context/worklog/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`sdt.context/notes/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`sdt.context/tasks/TODO.md`" + ` — active task list
  - ` + "`sdt.context/archive/<YYYYMMDD-HHMMSS>-<slug>.md`" + ` — archived task lists
- ` + "`sdt.context/`" + ` files use concise technical language. Cut fluff,
  keep meaning and readability (token-efficient).
- Every work file starts with YAML frontmatter:

` + "```yaml" + `
---
kind: worklog      # plan | worklog | notes | tasks
created_at: <ISO 8601>
context: what triggered this entry
project: <project>
---
` + "```" + `

Store durable facts in ` + "`sdt.context/memory/`" + ` (see
` + "`sdt.context/instructions/memory.md`" + `), not here.

## Commands

Create and manage work files with ` + "`sdt context`" + `:

- ` + "`sdt context new --type plan|worklog|notes --slug <slug> [--input ...]`" + ` — create a
  file with the correct name and frontmatter
- ` + "`sdt context path --type plan|worklog|notes|tasks|tmp|archive [--slug]`" + ` — print a
  path without creating anything
- ` + "`sdt context list --type plan|worklog|notes|tasks|archive`" + ` — list existing files
- ` + "`sdt context task add \"<step>\"`" + ` / ` + "`done|block|wip <id>`" + ` / ` + "`list`" + ` / ` + "`archive`" + ` — manage the
  active task list
`

// gitIgnore modes for --gitignore and the interactive entries prompt.
const (
	gitIgnoreModeNone    = "none"    // leave .gitignore untouched
	gitIgnoreModeTmp     = "tmp"     // ignore sdt.context/tmp/
	gitIgnoreModeDocs    = "docs"    // ignore sdt.context/docs/
	gitIgnoreModeWork    = "work"    // ignore tmp/ + docs/ (default)
	gitIgnoreModeContext = "context" // ignore the whole sdt.context/
)

// gitIgnoreTmpEntry keeps sdt.context/tmp out of version control. The pattern is
// not root-anchored so it also applies when sdt.context lives in a subdirectory.
const gitIgnoreTmpEntry = "sdt.context/tmp/"

// gitIgnoreDocsEntry keeps generated agent docs out of version control. The
// reference is regenerated per binary version, so it is never committed.
const gitIgnoreDocsEntry = "sdt.context/docs/"

// gitIgnoreContextEntry ignores the entire sdt.context/ working directory,
// including plans, work logs, notes and instruction files.
const gitIgnoreContextEntry = "sdt.context/"

// gitIgnoreWorkEntries lists the sdt.context/ entries ensured by default (work).
var gitIgnoreWorkEntries = []string{gitIgnoreTmpEntry, gitIgnoreDocsEntry}

// gitIgnoreEntriesForMode maps a gitignore mode to the entries it ensures.
// An empty result means no .gitignore changes (none).
func gitIgnoreEntriesForMode(mode string) []string {
	switch mode {
	case gitIgnoreModeNone:
		return nil
	case gitIgnoreModeTmp:
		return []string{gitIgnoreTmpEntry}
	case gitIgnoreModeDocs:
		return []string{gitIgnoreDocsEntry}
	case gitIgnoreModeContext:
		return []string{gitIgnoreContextEntry}
	default:
		return gitIgnoreWorkEntries
	}
}

// findGitRepoRoot walks up from the current directory looking for a .git entry
// (directory or worktree file). It returns the repository root, or "" when the
// current directory is not inside a git repository.
func findGitRepoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// ensureGitIgnore ensures the repository .gitignore ignores the sdt.context
// working directories selected by mode (tmp, docs, work, context). It creates
// the file when missing, appends each entry only when absent, and returns nil
// when no git repository is detected or mode is none.
func ensureGitIgnore(mode string) *FileResult {
	entries := gitIgnoreEntriesForMode(mode)
	if len(entries) == 0 {
		return nil
	}
	root := findGitRepoRoot()
	if root == "" {
		return nil
	}
	path := filepath.Join(root, ".gitignore")
	res := &FileResult{Path: path}
	existing := ""
	if data, err := os.ReadFile(path); err == nil { //#nosec G304 -- repo root derived from cwd walk-up
		existing = string(data)
	} else if !os.IsNotExist(err) {
		res.Status = statusError
		res.Reason = err.Error()
		return res
	}
	content := existing
	added := false
	for _, entry := range entries {
		if gitIgnoreHasEntry(content, entry) {
			continue
		}
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += entry + "\n"
		added = true
	}
	if !added {
		res.Status = statusSkipped
		res.Reason = "entries already present"
		return res
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //#nosec G306,G703 -- repo root derived from cwd walk-up
		res.Status = statusError
		res.Reason = err.Error()
		return res
	}
	if existing == "" {
		res.Status = statusCreated
	} else {
		res.Status = statusUpdated
	}
	return res
}

// gitIgnoreHasEntry reports whether content already contains entry as a line,
// tolerating a missing trailing slash and surrounding whitespace.
func gitIgnoreHasEntry(content, entry string) bool {
	base := strings.TrimSuffix(entry, "/")
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == entry || line == base {
			return true
		}
	}
	return false
}

// agentMergeTarget ensures AGENTS.md carries the single instructions block
// without destroying custom content. With force the block is refreshed.
func agentMergeTarget(target, project, group string, force bool) (FileResult, string) {
	res := FileResult{Path: target}
	content := ""
	if _, err := os.Stat(target); err == nil {
		data, rerr := os.ReadFile(target) //#nosec G304 -- user-chosen target file
		if rerr != nil {
			res.Status = statusError
			res.Reason = rerr.Error()
			return res, content
		}
		content = string(data)
	}

	newContent, changed := agentMergeBlock(content, agentSectionNameInstructions, agentBlockInstructions(project, group), force)
	if !changed {
		res.Status = statusSkipped
		res.Reason = "AGENTS.md already up to date"
	} else if strings.TrimSpace(content) == "" {
		res.Status = statusCreated
	} else {
		res.Status = statusUpdated
	}
	return res, newContent
}

func agentBlockInstructions(project, group string) string {
	if project == "" {
		project = "<project>"
	}
	frontmatter := "kind: worklog      # plan | worklog | notes | tasks\n"
	frontmatter += "created_at: <ISO 8601>\n"
	frontmatter += "context: what triggered this entry\n"
	frontmatter += "project: " + project + "\n"
	if group != "" {
		frontmatter += "group: " + group + "\n"
	}

	return `## Instructions

This project is managed with SDT. Read the relevant instruction file before acting:

- ` + "`sdt.context/instructions/project.md`" + ` — project identity and configuration
- ` + "`sdt.context/instructions/memory.md`" + ` — file-based memory usage (` + "`sdt.context/memory/`" + `)
- ` + "`sdt.context/instructions/reference.md`" + ` — SDT command reference
- ` + "`sdt.context/instructions/cli.md`" + ` — CLI usage and examples
- ` + "`sdt.context/docs/README.md`" + ` — per-command reference generated by ` + "`sdt context docs`" + ` (when present)

Work directories live under ` + "`sdt.context/`" + ` (plan/, analysis/, worklog/, notes/, tasks/,
archive/, memory/, tmp/). Never write or execute temporary files outside the project. Keep
all instruction files concise and technical.

### Workflow

Follow this loop for any non-trivial task:

1. **Plan** — write a short plan in ` + "`sdt.context/plan/`" + ` before starting (` + "`sdt context new --type plan --slug <slug>`" + `).
2. **Investigate** — read this AGENTS.md, read project memory (` + "`sdt.context/memory/`" + `) and inspect the code before changing anything.
3. **Act** — make the smallest change that satisfies the task.
4. **Verify** — run the project's build, test and lint commands. Discover them from the project (Taskfile, Makefile, package.json, go.mod or similar); if the project defines none, record them in ` + "`sdt.context/instructions/project.md`" + `.
5. **Annotate** — append a ` + "`sdt.context/worklog/`" + ` entry describing what changed and why.
6. **Remember** — store durable decisions in ` + "`sdt.context/memory/`" + `.
7. **Update** — keep this AGENTS.md current when conventions change.

### Planning, Work Logs & Annotations

Keep planning, work logs, task lists and annotations under ` + "`sdt.context/`" + `:

` + "```" + `
sdt.context/plan/<YYYY-MM-DD>-<slug>.md              # plan before starting work
sdt.context/analysis/<YYYY-MM-DD>-<slug>.md          # analysis / implementation plans
sdt.context/worklog/<YYYYMMDD-HHMMSS>-<slug>.md      # ordered log of completed work
sdt.context/notes/<YYYYMMDD-HHMMSS>-<slug>.md        # free-form annotations
sdt.context/tasks/TODO.md                            # active task list (checklist)
sdt.context/archive/<YYYYMMDD-HHMMSS>-<slug>.md      # completed task lists
` + "```" + `

Create work files with ` + "`sdt context new --type plan|analysis|worklog|notes --slug <slug>`" + ` —
naming and ` + "`created_at`" + ` frontmatter are guaranteed (` + "`sdt context path --type <type>`" + `
prints a path without creating anything).

### Task List (log-horizon)

For work with many steps, keep the active task list in
` + "`sdt.context/tasks/TODO.md`" + ` — every step needed to reach the objective,
with status. Manage it with ` + "`sdt context task`" + `.

- Status markers: ` + "`[ ]`" + ` todo · ` + "`[~]`" + ` in-progress · ` + "`[x]`" + ` done · ` + "`[!]`" + ` blocked
- Add steps with ` + "`sdt context task add \"<step>\"`" + `; update status with
  ` + "`sdt context task done|block|wip <id>`" + `.
- On completion, archive it with ` + "`sdt context task archive [--slug]`" + ` — the file
  moves to ` + "`sdt.context/archive/<YYYYMMDD-HHMMSS>-<slug>.md`" + `, preserving history
  for the next objective.

Temporary and scratch files live in ` + "`sdt.context/tmp/`" + ` — never outside the
project (no ` + "`/tmp`" + `, no other absolute paths).

Annotate continuously: plan before starting, append a dated worklog entry after
each change, and record decisions, dead-ends and constraints in
` + "`sdt.context/memory/`" + ` (see ` + "`sdt.context/instructions/memory.md`" + `). The goal is a
chronological, searchable history that lets
a future session (agent or human) reconstruct what happened and why.

Every work file starts with YAML frontmatter:

` + "```yaml" + `
---
` + frontmatter + `---
` + "```" + `

### Communication (default)

Code work: terse caveman ultra. Drop articles/filler/pleasantries/hedging.
Fragments OK, short synonyms, technical terms exact, code unchanged.
Pattern: ` + "`[thing] [action] [reason]. [next step]`" + `.
Not: "Sure! I'd be happy to help you with that."
Yes: "Bug in auth middleware. Fix:"
Code only — user-requested docs written normal (concise).

Commits: Conventional Commits. Subject ≤50 chars, imperative, lowercase after
type. Body only when "why" unclear. No period on subject.

Files in ` + "`sdt.context/`" + `: concise technical language. Cut fluff, keep meaning
and readability. These instructions and docs are concise on purpose.

### Patterns (keep updated)

This AGENTS.md is the source of truth for project conventions. Whenever a
decision is taken on a pattern to use in development, testing, documentation or
workflows, create or update the relevant section in the header of this AGENTS.md
(before the tagged block below) and record the change in
` + "`sdt.context/worklog/`" + `. Keep every section concise and technical.
`
}

// ── registration ───────────────────────────────────────────────────────────────

func init() {
	agentInitCmd.Flags().String("project", "", "Project name")
	agentInitCmd.Flags().String("group", "", "Group name")
	agentInitCmd.Flags().String("target", agentTargetDefault, "Output instruction file")
	agentInitCmd.Flags().String("gitignore", "", "Which sdt.context entries to add to .gitignore (none, tmp, docs, work, context); prompts interactively when omitted")
	agentInitCmd.Flags().Bool("force", false, "Refresh generated template content")
	agentInitCmd.Flags().Bool("yes", false, "Accept defaults without prompting")

	agentCmd.AddCommand(agentInitCmd)
	rootCmd.AddCommand(agentCmd)
}
