package cmd

import (
	"bufio"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
)

const (
	codeFence          = "```"
	agentTargetDefault = "AGENTS.md"
)

// ── tagged block helpers ───────────────────────────────────────────────────────

func sectionBlock(name, body string) string {
	body = strings.TrimSpace(body)
	return fmt.Sprintf("<!-- sdt:begin:%s -->\n\n%s\n\n<!-- sdt:end:%s -->\n", name, body, name)
}

func sectionBeginMarker(name string) string {
	return "<!-- sdt:begin:" + name + " -->"
}

func sectionEndMarker(name string) string {
	return "<!-- sdt:end:" + name + " -->"
}

func sectionRegexp(name string) *regexp.Regexp {
	return regexp.MustCompile(`(?s)\n?` + regexp.QuoteMeta(sectionBeginMarker(name)) + `.*?` + regexp.QuoteMeta(sectionEndMarker(name)) + `\n?`)
}

func hasSection(content, name string) bool {
	return sectionRegexp(name).MatchString(content)
}

// agentMergeBlock ensures the named block exists in content. With force it is
// refreshed, otherwise left untouched when already present. Returns the new
// content and whether it changed.
func agentMergeBlock(content, name, body string, force bool) (string, bool) {
	if hasSection(content, name) {
		if force {
			return sectionRegexp(name).ReplaceAllString(content, "\n"+sectionBlock(name, body)), true
		}
		return content, false
	}
	content = strings.TrimRight(content, "\n")
	if content != "" {
		content += "\n\n"
	}
	return content + sectionBlock(name, body), true
}

// ── target file helpers ────────────────────────────────────────────────────────

func agentTargetPath(cmd *cobra.Command) string {
	path := getStringFlag(cmd, "target", false)
	if path == "" {
		path = agentTargetDefault
	}
	return path
}

// ── agent command group ────────────────────────────────────────────────────────

var agentCmd = &cobra.Command{
	Use:   "agent",
	Short: "Agent instruction tools (AGENTS.md, instruction files)",
	Long: `Generate and maintain agent instruction files.

  agent init       bootstrap AGENTS.md + sdt.context/ instruction files

AGENTS.md carries the general agent instructions (5-phase lifecycle, knowledge
tiers, planning and work logs, communication, patterns) in a single tagged
block. The instruction files under ` + "`sdt.context/instructions/`" + ` cover CLI
usage plus per-type templates (analysis, plan, tasks, adr, architecture,
worklog, notes) and the command reference.
`,
}

// ── agent init (AGENTS.md + instruction files) ─────────────────────────────────

// instructionFile is one generated instruction file under sdt.context/instructions/.
type instructionFile struct {
	name string
	body string
}

func instructionFiles(project, group string) []instructionFile {
	return []instructionFile{
		{name: filepath.Base(sdtInstrProject), body: instrProjectTemplate(project, group)},
		{name: filepath.Base(sdtInstrAnalysis), body: instrAnalysisTemplate},
		{name: filepath.Base(sdtInstrPlan), body: instrPlanTemplate},
		{name: filepath.Base(sdtInstrTasks), body: instrTasksTemplate},
		{name: filepath.Base(sdtInstrAdr), body: instrAdrTemplate},
		{name: filepath.Base(sdtInstrArchitecture), body: instrArchitectureTemplate},
		{name: filepath.Base(sdtInstrWorklog), body: instrWorklogTemplate},
		{name: filepath.Base(sdtInstrNotes), body: instrNotesTemplate},
		{name: filepath.Base(sdtInstrReference), body: instrReferenceTemplate},
		{name: filepath.Base(sdtInstrCli), body: instrCLITemplate},
	}
}

// obsoleteInstructionFiles were generated by older versions of sdt agent init
// and are no longer part of the generated set. With --force they are removed.
var obsoleteInstructionFiles = []string{
	readmeFile,
	"commands.md",
	"workflow.md",
	"communication.md",
	"planning.md",
	"annotations.md",
	"self-update.md",
	"memory.md",
}

// writeInstructionFiles creates the instruction files under sdt.context/instructions/.
// It is non-destructive: existing files are preserved unless force is set.
func writeInstructionFiles(project, group string, force bool) []FileResult {
	var results []FileResult
	for _, f := range instructionFiles(project, group) {
		path := filepath.Join(sdtInstrDir, f.name)
		res := FileResult{Path: path}
		existed := false
		if _, err := os.Stat(path); err == nil {
			existed = true
			if !force {
				res.Status = statusSkipped
				res.Reason = "file already exists (use --force to overwrite)"
				results = append(results, res)
				continue
			}
		} else if !os.IsNotExist(err) {
			res.Status = statusError
			res.Reason = err.Error()
			results = append(results, res)
			continue
		}
		if err := os.MkdirAll(sdtInstrDir, 0o750); err != nil { //#nosec G301
			res.Status = statusError
			res.Reason = err.Error()
			results = append(results, res)
			continue
		}
		if err := os.WriteFile(path, []byte(f.body), 0o644); err != nil { //#nosec G306 -- user-chosen output
			res.Status = statusError
			res.Reason = err.Error()
			results = append(results, res)
			continue
		}
		if existed {
			res.Status = statusUpdated
		} else {
			res.Status = statusCreated
		}
		results = append(results, res)
	}
	if force {
		for _, name := range obsoleteInstructionFiles {
			path := filepath.Join(sdtInstrDir, name)
			if _, err := os.Stat(path); os.IsNotExist(err) {
				continue
			} else if err != nil {
				results = append(results, FileResult{Path: path, Status: statusError, Reason: err.Error()})
				continue
			}
			if err := os.Remove(path); err != nil {
				results = append(results, FileResult{Path: path, Status: statusError, Reason: err.Error()})
				continue
			}
			results = append(results, FileResult{Path: path, Status: statusRemoved, Reason: "obsolete (no longer generated)"})
		}
	}
	return results
}

var agentInitCmd = &cobra.Command{
	Use:   useInit,
	Short: "Bootstrap an SDT-managed project for AI agents",
	Long: `Bootstrap the current directory with everything an AI agent needs:

  .sdt.yaml                           project identity (project/group)
  AGENTS.md                           single tagged block of general instructions
  sdt.context/plan|worklog|notes|tasks|archive|tmp  working directories
  sdt.context/architecture/      living architecture documentation (no date)
  sdt.context/decisions/         numbered ADRs (NNNN-<slug>.md, append-only)
  sdt.context/analysis/          analysis documents and implementation plans
  sdt.context/instructions/      per-type instruction/template files
  .gitignore                          ignores chosen sdt.context dirs (current dir)

The command is idempotent and non-destructive: a second run fills in missing
content and never overwrites or removes existing files. Use --force to refresh
generated content and remove obsolete instruction files.

The .gitignore entries for the sdt.context working directories are decided
interactively: you are asked whether to ignore them at all, and which entries
(tmp/, docs/, or the whole sdt.context/ directory). The file is created or
updated in the execution directory — the same directory as .sdt.yaml — even
when it is not a git repository; parent directories are never resolved. Use
--gitignore none|tmp|docs|work|context to pick non-interactively; work (tmp/ +
docs/ entries) is the default. --yes accepts that default without prompting.

Values not provided via flags are prompted interactively with sensible defaults.
Use --yes to accept defaults without prompting (CI/non-interactive).

Examples:
  sdt agent init
  sdt agent init --project myapp
  sdt agent init --project myapp --group platform --yes`,
	Run: func(cmd *cobra.Command, args []string) {
		yes := getBoolFlag(cmd, "yes", false)
		project := getStringFlag(cmd, "project", false)
		group := getStringFlag(cmd, "group", false)
		force := getBoolFlag(cmd, "force", false)
		target := agentTargetPath(cmd)

		// 1. Resolve project identity: flags > interactive prompt > default.
		if project == "" {
			project = agentPrompt(cmd, yes, "Project name", defaultProjectName())
		}
		if group == "" {
			group = agentPrompt(cmd, yes, "Group name", defaultProjectName())
		}

		cfg := &ProjectConfig{Project: project, Group: group}
		if _, err := os.Stat(sdtConfigFile); err == nil {
			existing := loadProjectConfig(sdtConfigFile)
			if existing != nil {
				cfg.fill(existing)
			}
		}
		configResult := FileResult{Path: sdtConfigFile}
		if err := os.WriteFile(sdtConfigFile, []byte(buildProjectConfigContent(cfg.Project, cfg.Group)), 0o600); err != nil { //#nosec G306 -- user project config
			exitWithError(cmd, err)
		}
		configResult.Status = statusWritten

		// 2. sdt.context/ working directories (non-destructive).
		dirResults := ensureWorkDirs(force)

		// 3. .gitignore: entries maintained in the execution directory (the .sdt.yaml
		//    location) — asked/picked even outside a git repository, never
		//    resolved from a parent.
		var gitIgnoreResults []FileResult
		if res := ensureGitIgnore(resolveGitIgnoreMode(cmd, yes)); res != nil {
			gitIgnoreResults = append(gitIgnoreResults, *res)
		}

		// 4. Instruction files under sdt.context/instructions/.
		instrResults := writeInstructionFiles(cfg.Project, cfg.Group, force)

		// 5. AGENTS.md: ensure the single instructions block.
		mdResult, mdBody := agentMergeTarget(target, cfg.Project, cfg.Group, force)
		if err := os.WriteFile(target, []byte(mdBody), 0o644); err != nil { //#nosec G306 -- user-chosen output file
			exitWithError(cmd, err)
		}

		results := []FileResult{configResult}
		results = append(results, dirResults...)
		results = append(results, gitIgnoreResults...)
		results = append(results, instrResults...)
		results = append(results, mdResult)
		outputFileResults(cmd, results)
	},
}

// agentPrompt asks for a value on the terminal. When yes is set, or stdin is
// not a terminal, the default is returned without prompting.
func agentPrompt(cmd *cobra.Command, yes bool, label, def string) string {
	if yes || !stdinIsTTY() {
		return def
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "%s [%s]: ", label, def); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// resolveGitIgnoreMode decides which sdt.context entries go into .gitignore.
// A --gitignore flag value wins. When omitted the mode is asked interactively
// (confirm first, then which entries); non-interactive runs and --yes default
// to work, preserving the historical behavior.
func resolveGitIgnoreMode(cmd *cobra.Command, yes bool) string {
	raw := strings.ToLower(strings.TrimSpace(getStringFlag(cmd, "gitignore", false)))
	if raw != "" {
		switch raw {
		case gitIgnoreModeNone, gitIgnoreModeTmp, gitIgnoreModeDocs, gitIgnoreModeWork, gitIgnoreModeContext:
			return raw
		}
		exitWithError(cmd, fmt.Errorf("invalid --gitignore %q (want one of none|tmp|docs|work|context)", raw))
	}
	if yes || !stdinIsTTY() {
		return gitIgnoreModeWork
	}
	if !agentPromptBool(cmd, false, "Add sdt.context working directories to .gitignore?", true) {
		return gitIgnoreModeNone
	}
	return agentPromptGitIgnoreMode(cmd, false, gitIgnoreModeWork)
}

// agentPromptBool asks a yes/no question on the terminal. When yes is set, or
// stdin is not a terminal, the default is returned without prompting.
func agentPromptBool(cmd *cobra.Command, yes bool, label string, def bool) bool {
	if yes || !stdinIsTTY() {
		return def
	}
	d := "n"
	if def {
		d = "y"
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "%s [%s]: ", label, d); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes", "1":
		return true
	case "n", "no", "0":
		return false
	}
	if b, perr := strconv.ParseBool(strings.TrimSpace(line)); perr == nil {
		return b
	}
	return def
}

// agentPromptGitIgnoreMode asks which sdt.context entries to ignore. Accepted
// input is a comma-separated list of numbers or keywords: 1/tmp, 2/docs,
// 3/context (entire directory), or work for both tmp and docs. Empty input and
// unrecognized tokens fall back to def.
func agentPromptGitIgnoreMode(cmd *cobra.Command, yes bool, def string) string {
	if yes || !stdinIsTTY() {
		return def
	}
	if _, ferr := fmt.Fprintln(cmd.ErrOrStderr(), "Which sdt.context entries should be added to .gitignore?"); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "  1) %s\n", gitIgnoreTmpEntry); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "  2) %s\n", gitIgnoreDocsEntry); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprintf(cmd.ErrOrStderr(), "  3) %s (entire working directory)\n", gitIgnoreContextEntry); ferr != nil {
		_ = ferr
	}
	if _, ferr := fmt.Fprint(cmd.ErrOrStderr(), "Comma-separated (1,2,3) or keywords (tmp, docs, context) [1,2]: "); ferr != nil {
		_ = ferr
	}
	line, err := bufio.NewReader(cmd.InOrStdin()).ReadString('\n')
	if err != nil && err != io.EOF {
		return def
	}
	sel := strings.ToLower(strings.TrimSpace(line))
	if sel == "" {
		return def
	}
	selected := map[string]bool{}
	for _, part := range strings.Split(sel, ",") {
		choice := strings.TrimSpace(part)
		switch choice {
		case "1", gitIgnoreModeTmp:
			selected[gitIgnoreModeTmp] = true
		case "2", gitIgnoreModeDocs:
			selected[gitIgnoreModeDocs] = true
		case "3", gitIgnoreModeContext, "all":
			return gitIgnoreModeContext
		case gitIgnoreModeWork:
			return gitIgnoreModeWork
		}
	}
	if selected[gitIgnoreModeTmp] && selected[gitIgnoreModeDocs] {
		return gitIgnoreModeWork
	}
	if selected[gitIgnoreModeTmp] {
		return gitIgnoreModeTmp
	}
	if selected[gitIgnoreModeDocs] {
		return gitIgnoreModeDocs
	}
	return def
}

func stdinIsTTY() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return fi.Mode()&os.ModeCharDevice != 0
}

func defaultProjectName() string {
	cwd, err := os.Getwd()
	if err != nil {
		return ""
	}
	sum := sha256.Sum256([]byte(cwd))
	return fmt.Sprintf("%s_%x", filepath.Base(cwd), sum[:4])
}

// loadProjectConfig reads a project config file, returning nil on any error.
func loadProjectConfig(path string) *ProjectConfig {
	data, err := os.ReadFile(path) //#nosec G304 -- user-chosen config path
	if err != nil {
		return nil
	}
	var cfg ProjectConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil
	}
	return &cfg
}

// fill copies non-empty fields from existing into cfg, preserving prior values.
func (cfg *ProjectConfig) fill(existing *ProjectConfig) {
	if existing == nil {
		return
	}
	if existing.Project != "" {
		cfg.Project = existing.Project
	}
	if existing.Group != "" {
		cfg.Group = existing.Group
	}
}

// ensureWorkDirs creates the sdt.context/ working directory layout.
func ensureWorkDirs(force bool) []FileResult {
	dirs := []string{sdtWorkDir, sdtPlanDir, sdtAnalysisDir, sdtWorklogDir, sdtNotesDir, sdtTasksDir, sdtArchiveDir, sdtTmpDir, sdtInstrDir, sdtArchitectureDir, sdtDecisionsDir}
	var results []FileResult
	for _, d := range dirs {
		res := FileResult{Path: d + "/"}
		fi, err := os.Stat(d)
		if err == nil {
			if fi.IsDir() {
				res.Status = statusSkipped
				res.Reason = "directory already exists"
			} else {
				res.Status = statusError
				res.Reason = "exists and is not a directory"
			}
		} else if os.IsNotExist(err) {
			if err := os.MkdirAll(d, 0o750); err != nil { //#nosec G301
				res.Status = statusError
				res.Reason = err.Error()
			} else {
				res.Status = statusCreated
			}
		} else {
			res.Status = statusError
			res.Reason = err.Error()
		}
		results = append(results, res)
	}

	files := []struct {
		path    string
		content string
	}{
		{sdtWorkReadme, sdtWorkReadmeTemplate},
	}
	for _, f := range files {
		res := FileResult{Path: f.path}
		if _, err := os.Stat(f.path); os.IsNotExist(err) {
			if err := os.WriteFile(f.path, []byte(f.content), 0o644); err != nil { //#nosec G306 -- user-chosen output
				res.Status = statusError
				res.Reason = err.Error()
			} else {
				res.Status = statusCreated
			}
		} else if err == nil {
			res.Status = statusSkipped
			res.Reason = "file already exists"
		} else {
			res.Status = statusError
			res.Reason = err.Error()
		}
		results = append(results, res)
	}
	return results
}

const sdtWorkReadmeTemplate = `# sdt.context/ — Working Directory

This directory holds the agent's planning, work logs, task lists, notes,
instruction files and temporary files for this project.

## Layout

- ` + "`plan/`" + ` — plans written before starting non-trivial work
- ` + "`analysis/`" + ` — analysis documents and implementation plans
- ` + "`architecture/`" + ` — living architecture documentation (no date in name)
- ` + "`decisions/`" + ` — numbered ADRs (` + "`NNNN-<slug>.md`" + `, append-only)
- ` + "`worklog/`" + ` — chronological log of completed work
- ` + "`notes/`" + ` — free-form annotations
- ` + "`tasks/`" + ` — per-phase task checklists
- ` + "`archive/`" + ` — completed task lists (history)
- ` + "`instructions/`" + ` — agent instruction files (referenced by AGENTS.md)
- ` + "`index.md`" + ` — generated knowledge index (reindex/lint)
- ` + "`tmp/`" + ` — temporary and scratch files (never outside this project)

## Conventions

- Files are prefixed with date/time so they sort naturally and keep history:
  - ` + "`sdt.context/plan/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`sdt.context/analysis/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`sdt.context/worklog/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`sdt.context/notes/<YYYYMMDD-HHMMSS>-<slug>.md`" + `
  - ` + "`sdt.context/tasks/<phase>.md`" + ` — checklist per plan phase
  - ` + "`sdt.context/archive/<YYYYMMDD-HHMMSS>-<slug>.md`" + ` — archived task lists
- ` + "`architecture/`" + ` files are living documents without a date; ADRs are
  append-only and numbered (` + "`decisions/0001-<slug>.md`" + `).
- ` + "`sdt.context/`" + ` files use concise technical language. Cut fluff,
  keep meaning and readability (token-efficient).
- Every work file starts with YAML frontmatter:

` + "```yaml" + `
---
kind: worklog      # plan | worklog | notes | tasks
summary: <one-line description>   # mandatory (index source)
context: what triggered this entry
status: active
created: <ISO 8601>
updated: <ISO 8601>
links:                            # optional array of related docs
  - decisions/0001-something
project: <project>
---
` + "```" + `

Store durable facts in ` + "`decisions/`" + ` (ADRs) and ` + "`architecture/`" + `; the rest of
the directory keeps the chronological work history.

## Commands

Create and manage work files with ` + "`sdt context`" + `:

- ` + "`sdt context new --type plan|worklog|notes --slug <slug> [--input ...]`" + ` — create a
  file with the correct name and frontmatter
- ` + "`sdt context reindex`" + ` / ` + "`sdt context lint`" + ` — regenerate ` + "`index.md`" + ` / validate
  frontmatter and links
- ` + "`sdt context template --type <tipo>`" + ` — print the per-type instruction file
- ` + "`sdt context path --type plan|worklog|notes|tasks|tmp|archive [--slug]`" + ` — print a
  path without creating anything
- ` + "`sdt context list --type plan|worklog|notes|tasks|archive`" + ` — list existing files
- ` + "`sdt context task add --phase <phase> \"<step>\"`" + ` / ` + "`done|block|wip <id>`" + ` — manage a
  per-phase task checklist
`

// gitIgnore modes for --gitignore and the interactive entries prompt.
const (
	gitIgnoreModeNone    = "none"    // leave .gitignore untouched
	gitIgnoreModeTmp     = "tmp"     // ignore sdt.context/tmp/
	gitIgnoreModeDocs    = "docs"    // ignore sdt.context/docs/
	gitIgnoreModeWork    = "work"    // ignore tmp/ + docs/ (default)
	gitIgnoreModeContext = "context" // ignore the whole sdt.context/
)

// gitIgnoreTmpEntry keeps sdt.context/tmp out of version control. The pattern is
// not root-anchored so it also applies when sdt.context lives in a subdirectory.
const gitIgnoreTmpEntry = "sdt.context/tmp/"

// gitIgnoreDocsEntry keeps generated agent docs out of version control. The
// reference is regenerated per binary version, so it is never committed.
const gitIgnoreDocsEntry = "sdt.context/docs/"

// gitIgnoreContextEntry ignores the entire sdt.context/ working directory,
// including plans, work logs, notes and instruction files.
const gitIgnoreContextEntry = "sdt.context/"

// gitIgnoreWorkEntries lists the sdt.context/ entries ensured by default (work).
var gitIgnoreWorkEntries = []string{gitIgnoreTmpEntry, gitIgnoreDocsEntry}

// gitIgnore block markers bound the sdt-managed .gitignore entries so later
// runs can update them in place and the block is distinguishable from
// hand-written entries.
const (
	gitIgnoreBlockStart = "# sdt:start"
	gitIgnoreBlockEnd   = "# sdt:end"
)

// gitIgnoreEntriesForMode maps a gitignore mode to the entries it ensures.
// An empty result means no .gitignore changes (none).
func gitIgnoreEntriesForMode(mode string) []string {
	switch mode {
	case gitIgnoreModeNone:
		return nil
	case gitIgnoreModeTmp:
		return []string{gitIgnoreTmpEntry}
	case gitIgnoreModeDocs:
		return []string{gitIgnoreDocsEntry}
	case gitIgnoreModeContext:
		return []string{gitIgnoreContextEntry}
	default:
		return gitIgnoreWorkEntries
	}
}

// ensureGitIgnore ensures the .gitignore file located in the current working
// directory (the .sdt.yaml location) ignores the sdt.context working
// directories selected by mode (tmp, docs, work, context). The file is
// maintained even outside a git repository and parent directories are never
// resolved. Entries live inside a `# sdt:start` / `# sdt:end` block: the block
// is appended when absent, missing entries are inserted inside an existing
// block, and nothing changes when every entry is already present. It returns
// nil only when mode is none.
func ensureGitIgnore(mode string) *FileResult {
	entries := gitIgnoreEntriesForMode(mode)
	if len(entries) == 0 {
		return nil
	}
	path := filepath.Join(".", ".gitignore")
	res := &FileResult{Path: path}
	existing := ""
	if data, err := os.ReadFile(path); err == nil { //#nosec G304 -- user project directory derived from cwd
		existing = string(data)
	} else if !os.IsNotExist(err) {
		res.Status = statusError
		res.Reason = err.Error()
		return res
	}
	missing := gitIgnoreMissingEntries(existing, entries)
	if len(missing) == 0 {
		res.Status = statusSkipped
		res.Reason = "entries already present"
		return res
	}
	inner := strings.Join(missing, "\n")
	content := existing
	if strings.Contains(content, gitIgnoreBlockEnd) {
		content = strings.Replace(content, gitIgnoreBlockEnd, inner+"\n"+gitIgnoreBlockEnd, 1)
	} else {
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += gitIgnoreBlockStart + "\n" + inner + "\n" + gitIgnoreBlockEnd + "\n"
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //#nosec G306,G703 -- user project directory derived from cwd
		res.Status = statusError
		res.Reason = err.Error()
		return res
	}
	if existing == "" {
		res.Status = statusCreated
	} else {
		res.Status = statusUpdated
	}
	return res
}

// gitIgnoreMissingEntries returns the entries not already present as a line in
// content (tolerating a missing trailing slash), independent of the sdt block.
func gitIgnoreMissingEntries(content string, entries []string) []string {
	var missing []string
	for _, entry := range entries {
		if !gitIgnoreHasEntry(content, entry) {
			missing = append(missing, entry)
		}
	}
	return missing
}

// gitIgnoreHasEntry reports whether content already contains entry as a line,
// tolerating a missing trailing slash and surrounding whitespace.
func gitIgnoreHasEntry(content, entry string) bool {
	base := strings.TrimSuffix(entry, "/")
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == entry || line == base {
			return true
		}
	}
	return false
}

// agentMergeTarget ensures AGENTS.md carries the single instructions block
// without destroying custom content. With force the block is refreshed.
func agentMergeTarget(target, project, group string, force bool) (FileResult, string) {
	res := FileResult{Path: target}
	content := ""
	if _, err := os.Stat(target); err == nil {
		data, rerr := os.ReadFile(target) //#nosec G304 -- user-chosen target file
		if rerr != nil {
			res.Status = statusError
			res.Reason = rerr.Error()
			return res, content
		}
		content = string(data)
	}

	newContent, changed := agentMergeBlock(content, agentSectionNameInstructions, agentBlockInstructions(project, group), force)
	if !changed {
		res.Status = statusSkipped
		res.Reason = "AGENTS.md already up to date"
	} else if strings.TrimSpace(content) == "" {
		res.Status = statusCreated
	} else {
		res.Status = statusUpdated
	}
	return res, newContent
}

func agentBlockInstructions(project, group string) string {
	if project == "" {
		project = "<project>"
	}
	frontmatter := "kind: worklog      # plan | worklog | notes | tasks | adr | architecture\n"
	frontmatter += "summary: <one-line description>   # MANDATORY — the index source\n"
	frontmatter += "context: what triggered this entry\n"
	frontmatter += "status: active\n"
	frontmatter += "created: <ISO 8601>\n"
	frontmatter += "updated: <ISO 8601>\n"
	frontmatter += "links:             # optional array\n"
	frontmatter += "  - decisions/0001-something\n"
	frontmatter += "project: " + project + "\n"
	if group != "" {
		frontmatter += "group: " + group + "\n"
	}

	return `## Instructions

This project is managed with SDT. Read the relevant instruction file before acting:

- ` + "`sdt.context/instructions/project.md`" + ` — project identity and configuration
- ` + "`sdt.context/instructions/reference.md`" + ` — SDT command reference
- ` + "`sdt.context/instructions/cli.md`" + ` — CLI usage and examples
- ` + "`sdt.context/instructions/analysis.md`" + ` — analysis documents (structure + initial scan)
- ` + "`sdt.context/instructions/plan.md`" + ` — plans + the 5-phase development lifecycle
- ` + "`sdt.context/instructions/tasks.md`" + ` — per-phase task checklists (verify-step)
- ` + "`sdt.context/instructions/adr.md`" + ` — ADRs (numbered, append-only, sync → architecture)
- ` + "`sdt.context/instructions/architecture.md`" + ` — living architecture docs (tier: essential)
- ` + "`sdt.context/instructions/worklog.md`" + ` — work logs (final reports, append-only)
- ` + "`sdt.context/instructions/notes.md`" + ` — free-form annotations
- ` + "`sdt.context/index.md`" + ` — generated knowledge index (` + "`sdt context reindex`" + `)
- ` + "`sdt.context/docs/README.md`" + ` — per-command reference generated by ` + "`sdt context docs`" + ` (when present)

Work directories live under ` + "`sdt.context/`" + ` (` + "`plan/`" + `, ` + "`analysis/`" + `, ` + "`sdt.context/architecture/`" + `,
` + "`sdt.context/decisions/`" + `, worklog/, notes/, tasks/, archive/, tmp/). Never write or execute
temporary files outside the project. Keep all instruction files concise and technical.

### 5-phase development lifecycle

Follow this cycle for any non-trivial task:

1. **Analysis** — perform it; integrate/modify existing analysis files.
2. **Plan** — create from the analysis; integrate/modify as needed.
3. **Tasks** — from the plan create **one checklist file per phase** in
   ` + "`sdt.context/tasks/<phase>.md`" + ` (` + "`sdt context task`" + `).
4. **Execution** — develop the project; create ` + "`sdt.context/architecture/`" + ` and ` + "`sdt.context/decisions/`" + `
   (ADRs) as needed; **update the tasks and plan files** in place.
5. **Final reports** — append ` + "`sdt.context/worklog/`" + ` and ` + "`notes/`" + ` entries.

Before closing a phase run the **verify-step**: completeness, coherence, correctness
(prioritize CRITICAL / WARNING / SUGGESTION, degrade gracefully). Then reindex: run
` + "`sdt context reindex`" + ` and ` + "`sdt context lint`" + `.

When running the project's build, test and lint commands, discover them from the
project (Taskfile, Makefile, package.json, go.mod or similar); if the project defines
none, record them in ` + "`sdt.context/instructions/project.md`" + `.

### Knowledge tiers

` + "`sdt.context/index.md`" + ` is the single entry point (generated). At session start read it,
then the **essential** tier first ( ` + "`sdt.context/architecture/`" + ` + ` + "`sdt.context/decisions/`" + ` — always
versioned),
then only what is needed of the lower tiers (analysis, plan, notes, tasks). ` + "`worklog/`" + ` /
` + "`archive/`" + ` are history. ` + "`summary`" + ` frontmatter is mandatory everywhere; ` + "`links`" + `
is an optional array validated by lint.

Every work file starts with YAML frontmatter:

` + "```yaml" + `
---
` + frontmatter + `---
` + "```" + `

### Communication (default)

Code work: terse caveman ultra. Drop articles/filler/pleasantries/hedging.
Fragments OK, short synonyms, technical terms exact, code unchanged.
Pattern: ` + "`[thing] [action] [reason]. [next step]`" + `.
Not: "Sure! I'd be happy to help you with that."
Yes: "Bug in auth middleware. Fix:"
Code only — user-requested docs written normal (concise).

Commits: Conventional Commits. Subject ≤50 chars, imperative, lowercase after
type. Body only when "why" unclear. No period on subject.

Files in ` + "`sdt.context/`" + `: concise technical language. Cut fluff, keep meaning
and readability. These instructions and docs are concise on purpose.

### Patterns (keep updated)

This AGENTS.md is the source of truth for project conventions. Whenever a
decision is taken on a pattern to use in development, testing, documentation or
workflows, create or update the relevant section in the header of this AGENTS.md
(before the tagged block below) and record the change in
` + "`sdt.context/worklog/`" + `. Keep every section concise and technical.
`
}

// ── registration ───────────────────────────────────────────────────────────────

func init() {
	agentInitCmd.Flags().String("project", "", "Project name")
	agentInitCmd.Flags().String("group", "", "Group name")
	agentInitCmd.Flags().String("target", agentTargetDefault, "Output instruction file")
	agentInitCmd.Flags().String("gitignore", "", "Which sdt.context entries to add to .gitignore (none, tmp, docs, work, context); prompts interactively when omitted")
	agentInitCmd.Flags().Bool("force", false, "Refresh generated template content")
	agentInitCmd.Flags().Bool("yes", false, "Accept defaults without prompting")

	agentCmd.AddCommand(agentInitCmd)
	rootCmd.AddCommand(agentCmd)
}
