package cmd

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/goccy/go-yaml"
	"github.com/sandrolain/sdt/internal/mdindex"
	"github.com/spf13/cobra"
	"uuid"
)

// ctxFrontmatterUID is the immutable-identifier frontmatter key.
const ctxFrontmatterUID = "uid"

// ctxUIDBackfillMarker records that the one-shot `context uid backfill` has run.
// Lint flips a missing `uid` from SUGGESTION to WARNING once it exists.
var ctxUIDBackfillMarker = filepath.Join(mdindex.CacheDir, "uid-backfill.json")

// newUID returns a canonical lowercase UUIDv7 string (RFC 9562) generated by
// the standard-library uuid package. It is the immutable identifier stamped on
// every CLI-created context document.
func newUID() string {
	return uuid.NewV7().String()
}

// validUIDv7 reports whether s is a canonical RFC 9562 UUIDv7: the lowercase
// 8-4-4-4-12 form whose version nibble is 7. Parse canonicalizes, so a value
// that does not round-trip (uppercase, braces, urn: prefix) is rejected.
func validUIDv7(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return false
	}
	u, err := uuid.Parse(s)
	if err != nil {
		return false
	}
	return u[6]>>4 == 7 && u.String() == s
}

// ctxUIDEligibleKind reports whether a document kind is in the identifier
// scope: every kind creatable via `context new` plus `context task` (wiki and
// architecture included). commands, tmp, index and init-generated surfaces are
// out of scope.
func ctxUIDEligibleKind(kind string) bool {
	if kind == ctxTypeTasks {
		return true
	}
	t, ok := ctxTypeLookup(kind)
	return ok && t.newSupported
}

// uidBackfillDone reports whether the uid backfill marker exists. The marker is
// written by `sdt context uid backfill` on a real (non-dry) run.
func uidBackfillDone() bool {
	_, err := os.Stat(ctxUIDBackfillMarker)
	return err == nil
}

// stampUIDMissing inserts a fresh canonical uid immediately after the `kind:`
// line when the frontmatter carries none. It returns the new content and whether
// it changed; a document with an existing `uid` (or without a usable
// frontmatter block) is returned untouched, which keeps stamping idempotent.
func stampUIDMissing(content string) (string, bool) {
	lines := strings.Split(content, "\n")
	if len(lines) < 3 || strings.TrimSpace(lines[0]) != ctxFrontmatterDelim {
		return content, false
	}
	end, kindIdx := -1, -1
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == ctxFrontmatterDelim {
			end = i
			break
		}
		switch strings.TrimSpace(strings.SplitN(lines[i], ":", 2)[0]) {
		case ctxFrontmatterUID:
			return content, false
		case ctxFrontmatterKind:
			kindIdx = i
		}
	}
	if end < 0 || kindIdx < 0 {
		return content, false
	}
	out := make([]string, 0, len(lines)+1)
	out = append(out, lines[:kindIdx+1]...)
	out = append(out, "uid: "+newUID())
	out = append(out, lines[kindIdx+1:]...)
	return strings.Join(out, "\n"), true
}

// ctxUIDFiles lists every identifier-eligible document (recursively, so nested
// wiki pages are included) in a stable order. Missing directories are skipped.
func ctxUIDFiles() ([]string, error) {
	var files []string
	for _, t := range contextTypeList {
		if !ctxUIDEligibleKind(t.kind) {
			continue
		}
		walkErr := filepath.WalkDir(t.dir, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				if os.IsNotExist(err) {
					return nil
				}
				return err
			}
			if d.IsDir() || filepath.Ext(path) != sdtMarkdownExt {
				return nil
			}
			files = append(files, path)
			return nil
		})
		if walkErr != nil {
			return nil, walkErr
		}
	}
	sort.Strings(files)
	return files, nil
}

// ── context uid backfill ───────────────────────────────────────────────────────

type ctxUIDBackfillResult struct {
	Action   string   `json:"action" yaml:"action"`
	Scanned  int      `json:"scanned" yaml:"scanned"`
	Stamped  int      `json:"stamped" yaml:"stamped"`
	Skipped  int      `json:"skipped" yaml:"skipped"`
	Paths    []string `json:"paths,omitempty" yaml:"paths,omitempty"`
	Marker   string   `json:"marker,omitempty" yaml:"marker,omitempty"`
	Finished string   `json:"finished_at,omitempty" yaml:"finished_at,omitempty"`
}

// stampEligibleFiles is the shared backfill core: it stamps a missing uid on
// every eligible document. With dryRun it reports the would-change paths without
// writing (and without touching the marker).
func stampEligibleFiles(dryRun bool) (ctxUIDBackfillResult, error) {
	res := ctxUIDBackfillResult{Action: statusWritten, Marker: ctxUIDBackfillMarker}
	if dryRun {
		res.Action = statusDryRun
	}
	files, err := ctxUIDFiles()
	if err != nil {
		return res, err
	}
	for _, path := range files {
		data, rerr := os.ReadFile(path) //#nosec G304 -- fixed repo path
		if rerr != nil {
			return res, rerr
		}
		content := string(data)
		res.Scanned++
		if !ctxUIDEligibleKind(parseFrontmatterField(content, "kind")) {
			res.Skipped++
			continue
		}
		stamped, changed := stampUIDMissing(content)
		if !changed {
			res.Skipped++
			continue
		}
		res.Stamped++
		res.Paths = append(res.Paths, path)
		if dryRun {
			continue
		}
		if werr := writeWorkFile(path, stamped); werr != nil {
			return res, werr
		}
	}
	if dryRun {
		return res, nil
	}
	res.Finished = time.Now().UTC().Format(time.RFC3339)
	if err := writeUIDBackfillMarker(res.Finished, res.Stamped); err != nil {
		return res, err
	}
	return res, nil
}

// writeBackfillMarker persists a one-shot backfill completion marker: the
// RFC3339 timestamp and the number of items stamped. Shared by the uid and
// checklist backfills so lint can gate its presence warning on a completed run.
func writeBackfillMarker(markerPath, finishedAt string, count int) error {
	if err := os.MkdirAll(filepath.Dir(markerPath), 0o750); err != nil { //#nosec G301 -- derived cache dir
		return err
	}
	payload, err := json.MarshalIndent(map[string]any{"completed_at": finishedAt, "count": count}, "", "  ")
	if err != nil {
		return err
	}
	//#nosec G306 -- derived cache file
	return os.WriteFile(markerPath, append(payload, '\n'), 0o644)
}

// writeUIDBackfillMarker records a completed real backfill run so lint flips a
// missing uid from SUGGESTION to WARNING.
func writeUIDBackfillMarker(finishedAt string, count int) error {
	return writeBackfillMarker(ctxUIDBackfillMarker, finishedAt, count)
}

func outputUIDBackfill(cmd *cobra.Command, res ctxUIDBackfillResult) {
	switch getFormat(cmd) {
	case fmtJSON:
		out, err := json.MarshalIndent(res, "", "  ")
		exitWithError(cmd, err)
		outputBytes(cmd, out)
	case fmtYAML:
		out, err := yaml.Marshal(res)
		exitWithError(cmd, err)
		outputBytes(cmd, out)
	default:
		verb := "stamped"
		if res.Action == statusDryRun {
			verb = "would stamp"
		}
		outputString(cmd, fmt.Sprintf("%s %d uid(s); %d scanned, %d already present\n", verb, res.Stamped, res.Scanned, res.Skipped))
		for _, p := range res.Paths {
			outputString(cmd, p+"\n")
		}
	}
}

var contextUIDCmd = &cobra.Command{
	Use:   "uid",
	Short: "Manage document identifiers (uid)",
	Long: `Manage the immutable UUIDv7 ` + "`uid`" + ` identifier of context/ documents.

  sdt context uid backfill [--dry-run]   stamp a missing uid on every eligible document
                                         (idempotent; writes .sdt/cache/uid-backfill.json)`,
}

var contextUIDBackfillCmd = &cobra.Command{
	Use:   "backfill",
	Short: "Stamp a missing uid on every eligible context/ document",
	Long: `Stamp a missing UUIDv7 ` + "`uid`" + ` on every CLI-created context/ document
(every ` + "`context new`" + ` kind plus ` + "`context task`" + `; wiki and architecture included).
Existing uids are never rewritten, so the command is idempotent. A real run
writes the marker ` + "`.sdt/cache/uid-backfill.json`" + ` so lint starts treating a
missing uid as a WARNING; --dry-run only reports.

Examples:
  sdt context uid backfill
  sdt context uid backfill --dry-run
  sdt context uid backfill --dry-run --format json`,
	Args: cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		res, err := stampEligibleFiles(getBoolFlag(cmd, "dry-run", false))
		exitWithError(cmd, err)
		outputUIDBackfill(cmd, res)
	},
}

func init() {
	contextUIDBackfillCmd.Flags().Bool("dry-run", false, "Report without writing anything")
	contextUIDCmd.AddCommand(contextUIDBackfillCmd)
}
