package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestDocFileName(t *testing.T) {
	for in, want := range map[string]string{
		"context task add": "context-task-add.md",
		"jwt parse":        "jwt-parse.md",
		"memory set":       "memory-set.md",
	} {
		if got := docFileName(in); got != want {
			t.Errorf("docFileName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestCollectLeafCommands(t *testing.T) {
	var leaves []docsCommand
	for _, sub := range rootCmd.Commands() {
		collectLeafCommands(sub, "", &leaves)
	}
	if len(leaves) == 0 {
		t.Fatal("expected leaf commands")
	}
	names := map[string]bool{}
	for _, d := range leaves {
		if d.file == "" || d.path == "" {
			t.Errorf("empty path/file for %+v", d)
		}
		if names[d.file] {
			t.Errorf("duplicate file %q", d.file)
		}
		names[d.file] = true
		if d.c.Name() == "help" || d.c.Name() == "completion" {
			t.Errorf("unexpected default command in docs: %s", d.path)
		}
	}
	if !names["context-task-add.md"] {
		t.Error("expected context-task-add.md among leaves")
	}
}

func TestRenderCommandDoc(t *testing.T) {
	var leaves []docsCommand
	for _, sub := range rootCmd.Commands() {
		collectLeafCommands(sub, "", &leaves)
	}
	var target *docsCommand
	for i := range leaves {
		if leaves[i].path == "context task add" {
			target = &leaves[i]
			break
		}
	}
	if target == nil {
		t.Fatal("expected context task add command")
	}
	doc := renderCommandDoc(*target)
	for _, want := range []string{
		"# sdt context task add",
		"Generated by `sdt`",
		"## Usage",
		"## Description",
		"## Flags",
		"`objective`",
		"## Global Flags",
		"`format`",
		"## Input / Output",
		"stdin | `--input` | `--file` | `--inb64`",
	} {
		if !strings.Contains(doc, want) {
			t.Errorf("expected %q in command doc:\n%s", want, doc)
		}
	}
}

func TestRenderDocsIndex(t *testing.T) {
	var leaves []docsCommand
	for _, sub := range rootCmd.Commands() {
		collectLeafCommands(sub, "", &leaves)
	}
	idx := renderDocsIndex(leaves, "2026-08-06T07:00:00Z")
	for _, want := range []string{
		"# sdt — Generated Command Reference",
		"Generated by `sdt` dev at 2026-08-06T07:00:00Z",
		"## Global Conventions",
		"### context",
		"[sdt context task add](context-task-add.md)",
	} {
		if !strings.Contains(idx, want) {
			t.Errorf("expected %q in docs index", want)
		}
	}
	if strings.Contains(idx, "[sdt help]") || strings.Contains(idx, "[sdt completion]") {
		t.Error("expected no cobra default commands in docs index")
	}
}

func TestContextDocs(t *testing.T) {
	dir := runInTempDir(t)
	stubContextNow(t, time.Date(2026, 8, 6, 7, 0, 0, 0, time.UTC))

	var leaves []docsCommand
	for _, sub := range rootCmd.Commands() {
		collectLeafCommands(sub, "", &leaves)
	}

	out := execute(t, contextDocsCmd, nil)
	if !strings.Contains(string(out), "README.md") {
		t.Errorf("expected README in output: %s", out)
	}
	docsDir := filepath.Join(dir, "sdt.context", "docs")
	for _, f := range []string{"README.md", "context-task-add.md", "memory-set.md"} {
		if _, err := os.Stat(filepath.Join(docsDir, f)); err != nil {
			t.Errorf("expected %s generated: %v", f, err)
		}
	}
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != len(leaves)+1 {
		t.Errorf("expected %d files, got %d", len(leaves)+1, len(entries))
	}

	readme, _ := os.ReadFile(filepath.Join(docsDir, "README.md"))
	if !strings.Contains(string(readme), "Generated by `sdt` dev at 2026-08-06T07:00:00Z") {
		t.Errorf("expected deterministic timestamp in README:\n%s", readme)
	}
}

func TestContextDocsIdempotent(t *testing.T) {
	dir := runInTempDir(t)
	stubContextNow(t, time.Date(2026, 8, 6, 7, 0, 0, 0, time.UTC))

	execute(t, contextDocsCmd, nil)
	out := execute(t, contextDocsCmd, nil)
	if strings.Contains(string(out), "[created]") {
		t.Errorf("expected no created status on second run: %s", out)
	}
	if !strings.Contains(string(out), "[updated]") {
		t.Errorf("expected updated status on second run: %s", out)
	}
	docsDir := filepath.Join(dir, "sdt.context", "docs")
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		t.Fatal(err)
	}
	var leaves []docsCommand
	for _, sub := range rootCmd.Commands() {
		collectLeafCommands(sub, "", &leaves)
	}
	if len(entries) != len(leaves)+1 {
		t.Errorf("expected stable file count %d, got %d", len(leaves)+1, len(entries))
	}
}

func TestContextDocsClean(t *testing.T) {
	dir := runInTempDir(t)
	execute(t, contextDocsCmd, nil)
	stale := filepath.Join(dir, "sdt.context", "docs", "zz-stale.md")
	if err := os.WriteFile(stale, []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}
	out := execute(t, contextDocsCmd, nil, "--clean")
	if !strings.Contains(string(out), "zz-stale.md") || !strings.Contains(string(out), "stale") {
		t.Errorf("expected stale removal in output: %s", out)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("expected stale file removed")
	}
}

func TestContextDocsJSON(t *testing.T) {
	runInTempDir(t)
	out := execute(t, contextDocsCmd, nil, "--format", "json")
	var results []FileResult
	if err := json.Unmarshal(out, &results); err != nil {
		t.Fatalf("invalid JSON: %v\n%s", err, out)
	}
	if len(results) < 50 {
		t.Errorf("expected many generated files, got %d", len(results))
	}
	if results[0].Status != statusCreated {
		t.Errorf("expected created status, got %+v", results[0])
	}
}

func TestAgentBlockReferencesDocs(t *testing.T) {
	block := agentBlockInstructions("", "")
	if !strings.Contains(block, "sdt.context/docs/README.md") {
		t.Error("expected generated docs pointer in agent block")
	}
	if !strings.Contains(block, "sdt context docs") {
		t.Error("expected sdt context docs reference in agent block")
	}
}

// TestAgentBlockMatchesInstructionFiles (B7) ensures every instruction file
// referenced by the block is exactly the set generated by instructionFiles.
func TestAgentBlockMatchesInstructionFiles(t *testing.T) {
	block := agentBlockInstructions("p", "g")
	files := instructionFiles("p", "g")
	for _, f := range files {
		want := "sdt.context/instructions/" + f.name
		if !strings.Contains(block, "`"+want+"`") {
			t.Errorf("block does not reference generated file %s", want)
		}
	}
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "- `sdt.context/instructions/") {
			continue
		}
		start := strings.Index(line, "`")
		if start < 0 {
			continue
		}
		rest := line[start+1:]
		end := strings.Index(rest, "`")
		if end < 0 {
			continue
		}
		ref := rest[:end]
		found := false
		for _, f := range files {
			if ref == "sdt.context/instructions/"+f.name {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("block references %s which is not generated", ref)
		}
	}
}
