package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// docsCommand is a leaf command selected for documentation generation.
type docsCommand struct {
	path string // full use path without root, e.g. "context task add"
	file string // generated file name, e.g. "context-task-add.md"
	c    *cobra.Command
}

// docsFlag describes a flag for rendering a documentation table.
type docsFlag struct {
	Name      string
	Shorthand string
	Type      string
	Default   string
	Usage     string
}

// collectLeafCommands walks the command tree collecting runnable leaf commands.
func collectLeafCommands(c *cobra.Command, path string, out *[]docsCommand) {
	if c.Hidden {
		return
	}
	switch c.Name() {
	case "help", "completion":
		return
	}
	full := c.Name()
	if path != "" {
		full = path + " " + c.Name()
	}
	subs := c.Commands()
	if len(subs) == 0 && c.Run != nil {
		*out = append(*out, docsCommand{path: full, file: docFileName(full), c: c})
		return
	}
	for _, sub := range subs {
		collectLeafCommands(sub, full, out)
	}
}

// docFileName derives the markdown file name from a command path
// ("context task add" -> "context-task-add.md").
func docFileName(path string) string {
	return strings.ReplaceAll(path, " ", "-") + ".md"
}

// collectFlags returns the visible flags of a flag set ordered by name.
func collectFlags(fs *pflag.FlagSet) []docsFlag {
	var out []docsFlag
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		df := docsFlag{Name: f.Name, Shorthand: f.Shorthand, Type: f.Value.Type(), Usage: f.Usage}
		if f.DefValue != "" && f.DefValue != "[]" && f.DefValue != "false" {
			df.Default = f.DefValue
		}
		out = append(out, df)
	})
	return out
}

// markdownCell escapes a value for use inside a markdown table cell.
func markdownCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.ReplaceAll(s, "\n", " ")
}

// renderCommandDoc renders the markdown reference for a single command.
func renderCommandDoc(d docsCommand) string {
	c := d.c
	var b strings.Builder
	fmt.Fprintf(&b, "# sdt %s\n\n", d.path)
	fmt.Fprintf(&b, "> Generated by `sdt` %s. Regenerate with `sdt context docs`.\n\n", version)
	b.WriteString("## Usage\n\n" + codeFence + "\nsdt " + d.path + " [flags]\n" + codeFence + "\n\n")
	b.WriteString("## Description\n\n" + c.Short + "\n")
	if c.Long != "" && c.Long != c.Short {
		b.WriteString("\n" + c.Long + "\n")
	}
	b.WriteString("\n")
	if len(c.Aliases) > 0 {
		b.WriteString("## Aliases\n\n")
		for _, a := range c.Aliases {
			fmt.Fprintf(&b, "- `%s`\n", a)
		}
		b.WriteString("\n")
	}
	if flags := collectFlags(c.Flags()); len(flags) > 0 {
		b.WriteString("## Flags\n\n")
		b.WriteString("| Flag | Shorthand | Type | Default | Description |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, f := range flags {
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", markdownCell(f.Name), markdownCell(f.Shorthand), markdownCell(f.Type), markdownCell(f.Default), markdownCell(f.Usage))
		}
		b.WriteString("\n")
	}
	if flags := collectFlags(c.Root().PersistentFlags()); len(flags) > 0 {
		b.WriteString("## Global Flags\n\n")
		b.WriteString("| Flag | Type | Default | Description |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, f := range flags {
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", markdownCell(f.Name), markdownCell(f.Type), markdownCell(f.Default), markdownCell(f.Usage))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Input / Output\n\n")
	b.WriteString("- Input text: stdin | `--input` | `--file` | `--inb64` (in that precedence).\n")
	b.WriteString("- Machine-readable output: `--format json` or `--format yaml`.\n")
	b.WriteString("- Exit code `0` on success, `1` on error (message on stderr).\n\n")
	return b.String()
}

// renderDocsIndex renders the sdt.context/docs/README.md index.
func renderDocsIndex(cmds []docsCommand, generated string) string {
	var b strings.Builder
	b.WriteString("# sdt — Generated Command Reference\n\n")
	fmt.Fprintf(&b, "> Generated by `sdt` %s at %s. Regenerate with `sdt context docs`.\n\n", version, generated)
	b.WriteString("## Global Conventions\n\n")
	b.WriteString("- Input text: stdin | `--input` | `--file` | `--inb64` (in that precedence).\n")
	b.WriteString("- Output: `--format text|json|yaml` (default text). Use `--format json`/`yaml` for machine-readable output.\n")
	b.WriteString("- `--quiet` suppresses informational output; `--no-color` disables ANSI color codes.\n")
	b.WriteString("- Exit code `0` on success, `1` on error (message on stderr).\n")
	b.WriteString("- Paths are relative to the project root (e.g. `sdt.context/...`).\n\n")
	b.WriteString("## Commands\n\n")

	grouped := map[string][]docsCommand{}
	var order []string
	for _, d := range cmds {
		first := strings.SplitN(d.path, " ", 2)[0]
		if _, ok := grouped[first]; !ok {
			order = append(order, first)
		}
		grouped[first] = append(grouped[first], d)
	}
	sort.Strings(order)
	for _, g := range order {
		fmt.Fprintf(&b, "### %s\n\n", g)
		for _, d := range grouped[g] {
			fmt.Fprintf(&b, "- [sdt %s](%s) — %s\n", d.path, d.file, d.c.Short)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// listContextDocsStale returns generated .md files in out that are not part of
// files (stale after command changes).
func listContextDocsStale(out string, files map[string]string) ([]string, error) {
	entries, err := os.ReadDir(out)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var stale []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		if _, ok := files[e.Name()]; !ok {
			stale = append(stale, e.Name())
		}
	}
	return stale, nil
}

var contextDocsCmd = &cobra.Command{
	Use:   "docs",
	Short: "Generate agent docs in sdt.context/docs/",
	Long: `Generate a per-command reference under sdt.context/docs/ (gitignored) for AI
agents: a README index plus one markdown file per leaf command. The output is
regenerated from the command tree and tagged with the binary version so agents
can detect and refresh stale docs.

The directory is generated, not edited. Use --clean to remove generated files
that no longer correspond to a command.

Examples:
  sdt context docs
  sdt context docs --clean
  sdt context docs --format json`,
	Args: cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		out := getStringFlag(cmd, "out", false)
		clean := getBoolFlag(cmd, "clean", false)

		var leaves []docsCommand
		for _, sub := range cmd.Root().Commands() {
			collectLeafCommands(sub, "", &leaves)
		}
		sort.Slice(leaves, func(i, j int) bool { return leaves[i].path < leaves[j].path })

		files := map[string]string{
			readmeFile: renderDocsIndex(leaves, contextNow().UTC().Format(time.RFC3339)),
		}
		for _, d := range leaves {
			files[d.file] = renderCommandDoc(d)
		}

		if err := os.MkdirAll(out, 0o750); err != nil { //#nosec G301 -- user work dir
			exitWithError(cmd, err)
		}

		var results []FileResult
		if clean {
			stale, err := listContextDocsStale(out, files)
			exitWithError(cmd, err)
			for _, f := range stale {
				path := filepath.Join(out, f)
				exitWithError(cmd, os.Remove(path))
				results = append(results, FileResult{Path: path, Status: statusRemoved, Reason: "stale (no longer generated)"})
			}
		}

		names := make([]string, 0, len(files))
		for n := range files {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			path := filepath.Join(out, n)
			status := statusCreated
			if _, err := os.Stat(path); err == nil {
				status = statusUpdated
			} else if !os.IsNotExist(err) {
				exitWithError(cmd, err)
			}
			//#nosec G306 -- generated docs file
			if err := os.WriteFile(path, []byte(files[n]), 0o644); err != nil {
				exitWithError(cmd, err)
			}
			results = append(results, FileResult{Path: path, Status: status})
		}
		outputFileResults(cmd, results)
	},
}

func init() {
	contextDocsCmd.Flags().String("out", sdtDocsDir, "Output directory")
	contextDocsCmd.Flags().Bool("clean", false, "Remove generated files not part of this run")
	contextCmd.AddCommand(contextDocsCmd)
}
